param_error="Parametra kÄ¼Å«da"
component_num_limit="JÅ«s Ä«slaicÄ«gi nevarat izveidot vairÄk grupu."
friend_num_limit="JÅ«s Ä«slaicÄ«gi nevarat pievienot vairÄk draugu."
operation_error="DarbÄ«ba neizdevÄs. LÅ«dzu, pamÄ“Ä£iniet vÄ“lreiz vÄ“lÄk!"
char_limit="IevadÄ«tÄs rakstzÄ«mes pÄrsniedz maksimÄlo garuma ierobeÅ¾ojumu. MaksimÄlais skaits :number rakstzÄ«mes."
first_name_limit="JÅ«su ievadÄ«tais \"UzvÄrds\" pÄrsniedz maksimÄlo garuma ierobeÅ¾ojumu. MaksimÄlais skaits :number rakstzÄ«mes."
last_name_limit="JÅ«su ievadÄ«tais vÄrds pÄrsniedz maksimÄlo garuma ierobeÅ¾ojumu. MaksimÄlais skaits :number rakstzÄ«mes."
first_name_required="Lauks \"UzvÄrds\" nedrÄ«kst bÅ«t tukÅ¡s."
last_name_required="Lauks \"VÄrds\" nedrÄ«kst bÅ«t tukÅ¡s."
mobile_error="TÄlruÅ†a numura formÄta kÄ¼Å«da"
mobile_required="TÄlruÅ†a numurs nedrÄ«kst bÅ«t tukÅ¡s."
country_code_error="Valsts koda kÄ¼Å«da"
search_key="LÅ«dzu, ievadiet derÄ«gu lietotÄja ID vai mobilÄ tÄlruÅ†a numuru."
is_add_friend="DraudzÄ«bas pievienoÅ¡anas pieprasÄ«jums ir nosÅ«tÄ«ts."
system_error="SistÄ“mas kÄ¼Å«da"
msg_code_error="VerifikÄcijas koda formÄta kÄ¼Å«da"
first_name_length="UzvÄrds ir pÄrÄk garÅ¡."
friends_exist="LietotÄjs nav atrasts"
last_name_length="VÄrds \"VÄrds\" ir pÄrÄk garÅ¡."
content_length="MaksimÄlais 200Â rakstzÄ«mes"
he_friend_num_limit="JÅ«su vai lietotÄja draugu skaits ir sasniedzis ierobeÅ¾ojumu."
sign_error="Paraksta pÄrbaude neizdevÄs"
is_friends="LietotÄjs ir bijis jÅ«su draugs."
sms_friend_tips="Pievienojiet mani JustUs."
photo_tips="AugÅ¡upielÄdÄ“ts veiksmÄ«gi! Pievienojiet vairÄk draugu, lai kopÄ«gi dalÄ«tos reÄlajÄ dzÄ«vÄ“"
message_limit="JÅ«s pÄrÄk bieÅ¾i sÅ«tÄt Ä«sziÅ†as. LÅ«dzu, pamÄ“Ä£iniet vÄ“lreiz vÄ“lÄk."
copy_friend_tips="Pievienojiet mani JustUs."
no_add_friend_self="JÅ«s nevarat pievienot sevi kÄ draugu."
justus_slogan="IeraksÄ«sim Ä«sto dzÄ«vi kopÄ!"
justus_helper="JustUs rokasgrÄmata"
bind_mobile_error="TÄlruÅ†a numurs ir piesaistÄ«ts citam kontam."
bound_mobile="SaistÄ«Å¡ana neizdevÄs. LÅ«dzu, pamÄ“Ä£iniet vÄ“lreiz vÄ“lÄk."
not_add_self_friend="JÅ«s nevarat pievienot sevi kÄ draugu."
address_book_tips="SinhronizÄ“jiet savus kontaktus, lai atrastu draugus, kas jau izmanto JustUs. JÅ«su kontaktu dati tiks nosÅ«tÄ«ti JustUs, lai uzlabotu jÅ«su pieredzi un Ä¼autu jums un citiem atrast draugus."
follow_user="sekoja tev!"
notification_friends=":name ir kÄ¼uvis par jÅ«su â€œTikai mÄ“sâ€ draugu! MÄ“Ä£iniet nosÅ«tÄ«t viÅ†iem fotoattÄ“lus!"
notification_like=":name tu vienkÄrÅ¡i patiki!"
notification_comment=":name tikko komentÄ“ja jÅ«s, pÄrbaudiet to!"
notification_friend_apply=":name nosÅ«tÄ«ja jums draudzÄ«bas pieprasÄ«jumu."
notification_friend_send_picture=":name publicÄ“ja jaunu fotoattÄ“lu."
notification_user_register="NÄc un nofotografÄ“jies! Ierakstiet reÄlo dzÄ«vi kopÄ ar draugiem!"
notification_friend_register=":name ir arÄ« vietnÄ“ JustUs. Pievienot?"
notification_memory=":name, jums ir jauna atmiÅ†a."
notification_wait_add_friend=":name, tavi draugi gaida!"
notification_touch=":name pieskÄrÄs jÅ«su fotoattÄ“lamğŸ’“"
notification_follow_user=":name sekoja tev!"
photo_copy_1="Esmu pievienojis jÅ«s vietnei (JustUs). LejupielÄdÄ“jiet Å¡o lietotni, lai atÄ¼autu mana drauga pieprasÄ«jumu.Mans ID:"
photo_tips_1="AugÅ¡upielÄdÄ“ts veiksmÄ«gi! Pievienojiet vairÄk draugu, lai kopÄ«gi dalÄ«tos reÄlajÄ dzÄ«vÄ“"
photo_end_1="Vairs nav draugu brÄ«Å¾u. UzÅ†emiet fotoattÄ“lu vai pievienojiet citus draugus."
photo_copy_2="Pievienojiet mani JustUs.Mans ID:"
photo_tips_2="AugÅ¡upielÄdÄ“ts veiksmÄ«gi! Pievienojiet vairÄk draugu, lai kopÄ«gi dalÄ«tos reÄlajÄ dzÄ«vÄ“"
photo_end_2="Vairs nav draugu brÄ«Å¾u. UzÅ†emiet fotoattÄ“lu vai pievienojiet citus draugus."
photo_copy_3="Pievienojiet mani JustUs, lai mÄ“s varÄ“tu kopÄ«got fotoattÄ“lus mÅ«su sÄkuma ekrÄnÄ. Mans ID:"
photo_tips_3="NosÅ«tÄ«ts uz viÅ†u sÄkuma ekrÄniem! Pievienojiet vairÄk draugu, lai sÄkuma ekrÄnos kopÄ«gotu savu reÄlo dzÄ«vi."
photo_end_3="Vairs nav fotoattÄ“lu. Pievienojiet vairÄk draugu, lai sÄkuma ekrÄnos kopÄ«gotu savu reÄlo dzÄ«vi."
photo_copy_4="Pievienojiet mani JustUs, man ir fotoattÄ“li, ko nosÅ«tÄ«t uz jÅ«su sÄkuma ekrÄnu. Mans ID:"
photo_tips_4="NosÅ«tÄ«ts uz viÅ†u sÄkuma ekrÄniem! Pievienojiet vairÄk draugu, lai sÄkuma ekrÄnos kopÄ«gotu savu reÄlo dzÄ«vi."
photo_end_4="Vairs nav fotoattÄ“lu. Pievienojiet vairÄk draugu, lai sÄkuma ekrÄnos kopÄ«gotu savu reÄlo dzÄ«vi."
photo_copy_5="Pievienojiet mani JustUs, jaunajÄ logrÄ«ku sociÄlajÄ tÄ«klÄ! Mans ID:"
photo_tips_5="NosÅ«tÄ«ts uz viÅ†u sÄkuma ekrÄniem! Pievienojiet vairÄk draugu, lai sÄkuma ekrÄnos kopÄ«gotu savu reÄlo dzÄ«vi."
photo_end_5="Vairs nav fotoattÄ“lu. Uzaiciniet citus draugus, lai jÅ«su sÄkuma ekrÄnos kopÄ«gotu savu reÄlo dzÄ«vi."
photo_copy_6="Pievienojiet mani JustUsÂ â€” logrÄ«ku sociÄlajam tÄ«klam, viss ir gatavs, izÅ†emot jÅ«s!"
photo_tips_6="NosÅ«tÄ«ts uz viÅ†u sÄkuma ekrÄniem! Uzaiciniet vairÄk draugu, lai dalÄ«tos ar viÅ†iem savÄ reÄlajÄ dzÄ«vÄ“."
photo_end_6="Vairs nav fotoattÄ“lu. Pievienojiet vairÄk draugu, lai dalÄ«tos ar viÅ†iem savÄ reÄlajÄ dzÄ«vÄ“."
photo_copy_7="Pievienojiet mani JustUs, viss ir gatavs, izÅ†emot jÅ«s! Mans ID:"
photo_tips_7="NosÅ«tÄ«ts uz viÅ†u sÄkuma ekrÄniem! Uzaiciniet vairÄk draugu, lai dalÄ«tos ar viÅ†iem savÄ reÄlajÄ dzÄ«vÄ“."
photo_end_7="Vairs nav fotoattÄ“lu. Pievienojiet vairÄk draugu, lai dalÄ«tos ar viÅ†iem savÄ reÄlajÄ dzÄ«vÄ“."
photo_copy_8="Pievienojiet mani JustUsÂ â€” logrÄ«ku sociÄlajam tÄ«klam, kopÄ«gojiet ar mani reÄlo dzÄ«vi! Mans ID:"
photo_tips_8="NosÅ«tÄ«ts uz viÅ†u sÄkuma ekrÄniem! Uzaiciniet vairÄk draugu, lai dalÄ«tos ar viÅ†iem savÄ reÄlajÄ dzÄ«vÄ“."
photo_end_8="Vairs nav fotoattÄ“lu. Pievienojiet vairÄk draugu, lai dalÄ«tos ar viÅ†iem savÄ reÄlajÄ dzÄ«vÄ“."
photo_copy_9="PieÅ†emiet reÄlÄs dzÄ«ves fotoattÄ“lu izaicinÄjumu, pievienojiet mani vietnÄ“ JustUs. Mans ID:"
photo_tips_9="NosÅ«tÄ«ts uz viÅ†u sÄkuma ekrÄniem! Uzaiciniet vairÄk draugu, lai dalÄ«tos ar viÅ†iem savÄ reÄlajÄ dzÄ«vÄ“."
photo_end_9="Vairs nav fotoattÄ“lu. Pievienojiet vairÄk draugu, lai dalÄ«tos ar viÅ†iem savÄ reÄlajÄ dzÄ«vÄ“."
photo_copy_10="Es vÄ“los, lai jÅ«s bÅ«tu manÄ sÄkuma ekrÄnÄ, pievienojiet mani JustUs. Mans ID:"
photo_tips_10="NosÅ«tÄ«ts uz viÅ†u sÄkuma ekrÄniem! BÅ«tu jautrÄk, ja pievienotu vairÄk draugu."
photo_end_10="Vairs nav fotoattÄ“lu. Pievienojiet vairÄk draugu, lai dalÄ«tos kopÄ ar savu Ä«sto dzÄ«vi."
photo_copy_11="Es vÄ“los, lai jÅ«s bÅ«tu manÄ sÄkuma ekrÄnÄ, pievienojiet mani JustUs. Mans ID:"
photo_tips_11="NosÅ«tÄ«ts uz viÅ†u sÄkuma ekrÄniem! Pievienojiet citus draugus, lai nosÅ«tÄ«tu savus fotoattÄ“lus uz viÅ†u sÄkuma ekrÄniem."
photo_end_11="Å Ä·iet, ka jums ir beiguÅ¡ies draugu fotoattÄ“li! Pievienojiet vairÄk draugu, lai ierakstÄ«tu savu Ä«sto dzÄ«vi kopÄ."
photo_copy_12="Esiet mans sÄkuma ekrÄna draugs, pievienojiet mani JustUs. Mans ID:"
photo_tips_12="NosÅ«tÄ«ts uz viÅ†u sÄkuma ekrÄniem! Uzaiciniet vairÄk draugu uz savu sÄkuma ekrÄnu un nosÅ«tiet viÅ†iem jautrus fotoattÄ“lus!"
photo_end_12="Å Ä·iet, ka jums ir beiguÅ¡ies draugu fotoattÄ“li! Uzaiciniet vairÄk draugu uz savu sÄkuma ekrÄnu un nosÅ«tiet viÅ†iem jautrus fotoattÄ“lus."
photo_copy_13="Esiet mans sÄkuma ekrÄna draugs, pievienojiet mani JustUs. Mans ID:"
photo_tips_13="NosÅ«tÄ«ts uz viÅ†u sÄkuma ekrÄniem! BÅ«tu jautrÄk, ja pievienotu vairÄk sÄkuma ekrÄna draugu."
photo_end_13="Å Ä·iet, ka tev vajag vairÄk draugu! Uzaiciniet vairÄk draugu uz savu sÄkuma ekrÄnu un nosÅ«tiet viÅ†iem jautrus fotoattÄ“lus."
your_self_visible="Redzams tikai man"
update_new_version="Jauna dueta funkcija, lÅ«dzu, nÄc, lai jauninÄtu un izbaudÄ«tu to!"
