param_error="ParametrÅ³ klaida"
component_num_limit="Laikinai negalite sukurti daugiau grupiÅ³."
friend_num_limit="Laikinai negalite pridÄ—ti daugiau draugÅ³."
operation_error="Operacija nepavyko. Pabandykite dar kartÄ… vÄ—liau!"
char_limit="Ä®vesti simboliai virÅ¡ija didÅ¾iausiÄ… ilgio limitÄ…. Daugiausia :number simboliai."
first_name_limit="Ä®vesta â€PavardÄ—â€œ virÅ¡ija didÅ¾iausio ilgio limitÄ…. Daugiausia :number simboliai."
last_name_limit="Ä®vestas â€Vardasâ€œ virÅ¡ija didÅ¾iausio ilgio limitÄ…. Daugiausia :number simboliai."
first_name_required="Lauko â€PavardÄ—â€œ laukas negali bÅ«ti tuÅ¡Äias."
last_name_required="Lauko â€Vardasâ€œ laukas negali bÅ«ti tuÅ¡Äias."
mobile_error="Telefono numerio formato klaida"
mobile_required="Telefono numerio laukas negali bÅ«ti tuÅ¡Äias."
country_code_error="Å alies kodo klaida"
search_key="Ä®veskite galiojantÄ¯ vartotojo ID arba mobiliojo telefono numerÄ¯."
is_add_friend="PraÅ¡ymas pridÄ—ti draugÄ… iÅ¡siÅ³stas."
system_error="Sistemos klaida"
msg_code_error="Patvirtinimo kodo formato klaida"
first_name_length="â€PavardÄ—â€œ per ilga."
friends_exist="Vartotojas nerastas"
last_name_length="â€Vardasâ€œ per ilgas."
content_length="Daugiausia 200 simboliÅ³"
he_friend_num_limit="JÅ«sÅ³ arba vartotojo draugÅ³ skaiÄius pasiekÄ— limitÄ…."
sign_error="ParaÅ¡o patikrinimas nepavyko"
is_friends="Vartotojas buvo jÅ«sÅ³ draugas."
sms_friend_tips="PridÄ—kite mane prie JustUs."
photo_tips="Ä®kelta sÄ—kmingai! PridÄ—kite daugiau draugÅ³ ir dalinkitÄ—s tikru gyvenimu"
message_limit="Per daÅ¾nai siunÄiate tekstinius praneÅ¡imus. Pabandykite dar kartÄ… vÄ—liau."
copy_friend_tips="PridÄ—kite mane prie JustUs."
no_add_friend_self="Negalite pridÄ—ti savÄ™s kaip draugo."
justus_slogan="Ä®raÅ¡ykime tikrÄ… gyvenimÄ… kartu!"
justus_helper="JustUs vadovas"
bind_mobile_error="Telefono numeris susietas su kita paskyra."
bound_mobile="Ä®riÅ¡imas nepavyko. Pabandykite dar kartÄ… vÄ—liau."
not_add_self_friend="Negalite pridÄ—ti savÄ™s kaip draugo."
address_book_tips="Sinchronizuokite savo kontaktus, kad rastumÄ—te draugÅ³, kurie jau naudojasi JustUs. JÅ«sÅ³ kontaktÅ³ duomenys bus siunÄiami â€JustUsâ€œ, kad pagerintumÄ—te jÅ«sÅ³ patirtÄ¯ ir leistÅ³ jums bei kitiems susirasti draugÅ³."
follow_user="sekiau tave!"
notification_friends=":name tapo jÅ«sÅ³ draugu â€Tik mesâ€œ! Pabandykite nusiÅ³sti jiems nuotraukas!"
notification_like=":name tu tiesiog patikai!"
notification_comment=":name kÄ… tik pakomentavo jus, paÅ¾iÅ«rÄ—kite!"
notification_friend_apply=":name atsiuntÄ— jums praÅ¡ymÄ… draugauti."
notification_friend_send_picture=":name paskelbÄ— naujÄ… nuotraukÄ…."
notification_user_register="Ateik ir nusifotografuok! Ä®raÅ¡ykite tikrÄ… gyvenimÄ… su draugais kartu!"
notification_friend_register=":name taip pat yra JustUs. Papildyti?"
notification_memory=":name, turite naujÄ… atmintÄ¯."
notification_wait_add_friend=":name, jÅ«sÅ³ draugai laukia!"
notification_touch=":name palietÄ— tavo nuotraukÄ…ğŸ’“"
notification_follow_user=":name sekiau tave!"
photo_copy_1="AÅ¡ Ä¯traukiau jus Ä¯ (JustUs). AtsisiÅ³skite Å¡iÄ… programÄ…, kad galÄ—tumÄ—te praÅ¡yti draugo.Mano ID:"
photo_tips_1="Ä®kelta sÄ—kmingai! PridÄ—kite daugiau draugÅ³ ir dalinkitÄ—s tikru gyvenimu"
photo_end_1="Daugiau jokiÅ³ draugÅ³ akimirkÅ³. Nufotografuokite arba pridÄ—kite daugiau draugÅ³."
photo_copy_2="PridÄ—kite mane prie JustUs.Mano ID:"
photo_tips_2="Ä®kelta sÄ—kmingai! PridÄ—kite daugiau draugÅ³ ir dalinkitÄ—s tikru gyvenimu"
photo_end_2="Daugiau jokiÅ³ draugÅ³ akimirkÅ³. Nufotografuokite arba pridÄ—kite daugiau draugÅ³."
photo_copy_3="PridÄ—kite mane prie JustUs, kad galÄ—tume bendrinti nuotraukas pagrindiniame ekrane. Mano ID:"
photo_tips_3="IÅ¡siÅ³sta Ä¯ jÅ³ pagrindinius ekranus! PridÄ—kite daugiau draugÅ³, kad pradiniame ekrane pasidalintumÄ—te savo tikruoju gyvenimu."
photo_end_3="Daugiau nuotraukÅ³ nÄ—ra. PridÄ—kite daugiau draugÅ³, kad pradiniame ekrane pasidalintumÄ—te savo tikruoju gyvenimu."
photo_copy_4="PridÄ—kite mane prie JustUs, turiu nuotraukÅ³, kurias galite siÅ³sti Ä¯ jÅ«sÅ³ pagrindinÄ¯ ekranÄ…. Mano ID:"
photo_tips_4="IÅ¡siÅ³sta Ä¯ jÅ³ pagrindinius ekranus! PridÄ—kite daugiau draugÅ³, kad pradiniame ekrane pasidalintumÄ—te savo tikruoju gyvenimu."
photo_end_4="Daugiau nuotraukÅ³ nÄ—ra. PridÄ—kite daugiau draugÅ³, kad pradiniame ekrane pasidalintumÄ—te savo tikruoju gyvenimu."
photo_copy_5="PridÄ—kite mane prie JustUs, naujo valdiklio socialinio tinklo! Mano ID:"
photo_tips_5="IÅ¡siÅ³sta Ä¯ jÅ³ pagrindinius ekranus! PridÄ—kite daugiau draugÅ³, kad pradiniame ekrane pasidalintumÄ—te savo tikruoju gyvenimu."
photo_end_5="Daugiau nuotraukÅ³ nÄ—ra. Pakvieskite daugiau draugÅ³ pasidalyti savo tikruoju gyvenimu pagrindiniuose ekranuose."
photo_copy_6="PridÄ—kite mane prie JustUs â€“ valdiklio socialinio tinklo, viskas yra paruoÅ¡ta, iÅ¡skyrus jus!"
photo_tips_6="IÅ¡siÅ³sta Ä¯ jÅ³ pagrindinius ekranus! Pakvieskite daugiau draugÅ³ pasidalyti su jais savo tikruoju gyvenimu."
photo_end_6="Daugiau nuotraukÅ³ nÄ—ra. PridÄ—kite daugiau draugÅ³, kad su jais pasidalintumÄ—te savo tikruoju gyvenimu."
photo_copy_7="PridÄ—kite mane prie JustUs, viskas yra paruoÅ¡ta, iÅ¡skyrus jus! Mano ID:"
photo_tips_7="IÅ¡siÅ³sta Ä¯ jÅ³ pagrindinius ekranus! Pakvieskite daugiau draugÅ³ pasidalyti su jais savo tikruoju gyvenimu."
photo_end_7="Daugiau nuotraukÅ³ nÄ—ra. PridÄ—kite daugiau draugÅ³, kad su jais pasidalintumÄ—te savo tikruoju gyvenimu."
photo_copy_8="PridÄ—kite mane prie JustUs â€“ valdiklio socialinio tinklo, pasidalykite tikru gyvenimu su manimi! Mano ID:"
photo_tips_8="IÅ¡siÅ³sta Ä¯ jÅ³ pagrindinius ekranus! Pakvieskite daugiau draugÅ³ pasidalyti su jais savo tikruoju gyvenimu."
photo_end_8="Daugiau nuotraukÅ³ nÄ—ra. PridÄ—kite daugiau draugÅ³, kad su jais pasidalintumÄ—te savo tikruoju gyvenimu."
photo_copy_9="Priimkite realaus gyvenimo nuotraukÅ³ iÅ¡Å¡Å«kÄ¯, pridÄ—kite mane prie JustUs. Mano ID:"
photo_tips_9="IÅ¡siÅ³sta Ä¯ jÅ³ pagrindinius ekranus! Pakvieskite daugiau draugÅ³ pasidalyti su jais savo tikruoju gyvenimu."
photo_end_9="Daugiau nuotraukÅ³ nÄ—ra. PridÄ—kite daugiau draugÅ³, kad su jais pasidalintumÄ—te savo tikruoju gyvenimu."
photo_copy_10="Noriu, kad bÅ«tumÄ—te mano pagrindiniame ekrane, Ä¯traukite mane Ä¯ JustUs. Mano ID:"
photo_tips_10="IÅ¡siÅ³sta Ä¯ jÅ³ pagrindinius ekranus! BÅ«tÅ³ smagiau, jei pridÄ—tumÄ—te daugiau draugÅ³."
photo_end_10="Daugiau nuotraukÅ³ nÄ—ra. PridÄ—kite daugiau draugÅ³, kad kartu pasidalytumÄ—te savo tikruoju gyvenimu."
photo_copy_11="Noriu, kad bÅ«tumÄ—te mano pagrindiniame ekrane, Ä¯traukite mane Ä¯ JustUs. Mano ID:"
photo_tips_11="IÅ¡siÅ³sta Ä¯ jÅ³ pagrindinius ekranus! PridÄ—kite daugiau draugÅ³, kad galÄ—tumÄ—te siÅ³sti nuotraukas Ä¯ jÅ³ pagrindinÄ¯ ekranÄ…."
photo_end_11="Atrodo, kad pritrÅ«ko draugÅ³ nuotraukÅ³! PridÄ—kite daugiau draugÅ³, kad kartu Ä¯raÅ¡ytumÄ—te savo tikrÄ…jÄ¯ gyvenimÄ…."
photo_copy_12="BÅ«kite mano pagrindinio ekrano draugas, pridÄ—kite mane prie JustUs. Mano ID:"
photo_tips_12="IÅ¡siÅ³sta Ä¯ jÅ³ pagrindinius ekranus! Pakvieskite daugiau draugÅ³ Ä¯ pagrindinÄ¯ ekranÄ… ir siÅ³skite jiems smagiÅ³ nuotraukÅ³!"
photo_end_12="Atrodo, kad pritrÅ«ko draugÅ³ nuotraukÅ³! Pakvieskite daugiau draugÅ³ Ä¯ pagrindinÄ¯ ekranÄ… ir siÅ³skite jiems smagiÅ³ nuotraukÅ³."
photo_copy_13="BÅ«kite mano pagrindinio ekrano draugas, pridÄ—kite mane prie JustUs. Mano ID:"
photo_tips_13="IÅ¡siÅ³sta Ä¯ jÅ³ pagrindinius ekranus! BÅ«tÅ³ smagiau, jei pridÄ—tumÄ—te daugiau pagrindinio ekrano draugÅ³."
photo_end_13="Atrodo, kad tau reikia daugiau draugÅ³! Pakvieskite daugiau draugÅ³ Ä¯ pagrindinÄ¯ ekranÄ… ir siÅ³skite jiems smagiÅ³ nuotraukÅ³."
your_self_visible="Matoma tik man"
update_new_version="Nauja dueto funkcija, ateikite atnaujinti ir patirti!"
