param_error="Chyba parametru"
component_num_limit="DoÄasnÄ› nemÅ¯Å¾ete vytvoÅ™it dalÅ¡Ã­ skupiny."
friend_num_limit="DoÄasnÄ› nemÅ¯Å¾ete pÅ™idat dalÅ¡Ã­ pÅ™Ã¡tele."
operation_error="Operace se nezdaÅ™ila. ProsÃ­m zkuste to znovu pozdÄ›ji!"
char_limit="ZadanÃ© znaky pÅ™ekraÄujÃ­ limit maximÃ¡lnÃ­ dÃ©lky. Maximum :number znakÅ¯."
first_name_limit="ZadanÃ© â€PÅ™Ã­jmenÃ­â€œ pÅ™ekraÄuje limit maximÃ¡lnÃ­ dÃ©lky. Maximum :number znakÅ¯."
last_name_limit="ZadanÃ© â€JmÃ©noâ€œ pÅ™ekraÄuje limit maximÃ¡lnÃ­ dÃ©lky. Maximum :number znakÅ¯."
first_name_required="Pole â€PÅ™Ã­jmenÃ­â€œ nemÅ¯Å¾e bÃ½t prÃ¡zdnÃ©."
last_name_required="Pole â€KÅ™estnÃ­ jmÃ©noâ€œ nemÅ¯Å¾e bÃ½t prÃ¡zdnÃ©."
mobile_error="Chyba formÃ¡tu telefonnÃ­ho ÄÃ­sla"
mobile_required="TelefonnÃ­ ÄÃ­slo nesmÃ­ bÃ½t prÃ¡zdnÃ©."
country_code_error="Chyba kÃ³du zemÄ›"
search_key="Zadejte prosÃ­m platnÃ© ID uÅ¾ivatele nebo ÄÃ­slo mobilnÃ­ho telefonu."
is_add_friend="Å½Ã¡dost o pÅ™idÃ¡nÃ­ pÅ™Ã¡telstvÃ­ byla odeslÃ¡na."
system_error="Chyba systÃ©mu"
msg_code_error="Chyba formÃ¡tu ovÄ›Å™ovacÃ­ho kÃ³du"
first_name_length="PÅ™Ã­jmenÃ­ je pÅ™Ã­liÅ¡ dlouhÃ©."
friends_exist="UÅ¾ivatel nenalezen"
last_name_length="KÅ™estnÃ­ jmÃ©no je pÅ™Ã­liÅ¡ dlouhÃ©."
content_length="MaximÃ¡lnÄ› 200 znakÅ¯"
he_friend_num_limit="VÃ¡Å¡ nebo uÅ¾ivatelÅ¯v poÄet pÅ™Ã¡tel dosÃ¡hl limitu."
sign_error="OvÄ›Å™enÃ­ podpisu selhalo"
is_friends="UÅ¾ivatel byl vÃ¡Å¡ pÅ™Ã­tel."
sms_friend_tips="PÅ™idejte si mÄ› na JustUs."
photo_tips="ÃšspÄ›Å¡nÄ› nahrÃ¡no! PÅ™idejte si dalÅ¡Ã­ pÅ™Ã¡tele a sdÃ­lejte spolu skuteÄnÃ½ Å¾ivot"
message_limit="PÅ™Ã­liÅ¡ Äasto posÃ­lÃ¡te textovÃ© zprÃ¡vy. ProsÃ­m zkuste to znovu pozdÄ›ji."
copy_friend_tips="PÅ™idejte si mÄ› na JustUs."
no_add_friend_self="NemÅ¯Å¾ete se pÅ™idat jako pÅ™Ã­tele."
justus_slogan="PojÄme spoleÄnÄ› zaznamenat skuteÄnÃ½ Å¾ivot!"
justus_helper="PrÅ¯vodce JustUs"
bind_mobile_error="TelefonnÃ­ ÄÃ­slo bylo svÃ¡zÃ¡no s jinÃ½m ÃºÄtem."
bound_mobile="Vazba se nezdaÅ™ila. ProsÃ­m zkuste to znovu pozdÄ›ji."
not_add_self_friend="NemÅ¯Å¾ete se pÅ™idat jako pÅ™Ã­tele."
address_book_tips="Synchronizujte svÃ© kontakty a najdÄ›te pÅ™Ã¡tele, kteÅ™Ã­ jiÅ¾ jsou na JustUs. VaÅ¡e kontaktnÃ­ Ãºdaje budou odeslÃ¡ny spoleÄnosti JustUs, aby se zlepÅ¡ila vaÅ¡e zkuÅ¡enost a umoÅ¾nila vÃ¡m i ostatnÃ­m najÃ­t pÅ™Ã¡tele."
follow_user="sledoval tÄ›!"
notification_friends=":name se stal vaÅ¡Ã­m pÅ™Ã­telem â€Jen myâ€œ! Zkuste jim poslat fotky!"
notification_like=":name se ti prostÄ› lÃ­bilo!"
notification_comment=":name vÃ¡s prÃ¡vÄ› okomentoval, podÃ­vejte se!"
notification_friend_apply=":name vÃ¡m poslal Å¾Ã¡dost o pÅ™Ã¡telstvÃ­."
notification_friend_send_picture=":name zveÅ™ejnil(a) novou fotku."
notification_user_register="PÅ™ijÄte se vyfotit! Nahrajte skuteÄnÃ½ Å¾ivot se svÃ½mi pÅ™Ã¡teli spoleÄnÄ›!"
notification_friend_register=":name je takÃ© na JustUs. PÅ™idat?"
notification_memory=":name, mÃ¡te novou pamÄ›Å¥."
notification_wait_add_friend=":name, vaÅ¡i pÅ™Ã¡telÃ© ÄekajÃ­!"
notification_touch=":name zaklepal na vaÅ¡i fotkuğŸ’“"
notification_follow_user=":name sledoval tÄ›!"
photo_copy_1="PÅ™idal jsem si vÃ¡s na (JustUs). StÃ¡hnÄ›te si tuto aplikaci a povolte moji Å¾Ã¡dost o pÅ™Ã¡telstvÃ­.MÅ¯j prÅ¯kaz:"
photo_tips_1="ÃšspÄ›Å¡nÄ› nahrÃ¡no! PÅ™idejte si dalÅ¡Ã­ pÅ™Ã¡tele a sdÃ­lejte spolu skuteÄnÃ½ Å¾ivot"
photo_end_1="Å½Ã¡dnÃ© dalÅ¡Ã­ chvÃ­le pÅ™Ã¡tel. PoÅ™iÄte fotku nebo pÅ™idejte dalÅ¡Ã­ pÅ™Ã¡tele."
photo_copy_2="PÅ™idejte si mÄ› na JustUs.MÅ¯j prÅ¯kaz:"
photo_tips_2="ÃšspÄ›Å¡nÄ› nahrÃ¡no! PÅ™idejte si dalÅ¡Ã­ pÅ™Ã¡tele a sdÃ­lejte spolu skuteÄnÃ½ Å¾ivot"
photo_end_2="Å½Ã¡dnÃ© dalÅ¡Ã­ chvÃ­le pÅ™Ã¡tel. PoÅ™iÄte fotku nebo pÅ™idejte dalÅ¡Ã­ pÅ™Ã¡tele."
photo_copy_3="PÅ™idejte si mÄ› na JustUs, abychom mohli sdÃ­let fotografie na domovskÃ© obrazovce. MÅ¯j prÅ¯kaz:"
photo_tips_3="OdeslÃ¡no na jejich domovskÃ© obrazovky! PÅ™idejte si dalÅ¡Ã­ pÅ™Ã¡tele a sdÃ­lejte svÃ© skuteÄnÃ© Å¾ivoty na svÃ½ch domovskÃ½ch obrazovkÃ¡ch."
photo_end_3="Å½Ã¡dnÃ© dalÅ¡Ã­ fotky. PÅ™idejte si dalÅ¡Ã­ pÅ™Ã¡tele a sdÃ­lejte svÃ© skuteÄnÃ© Å¾ivoty na svÃ½ch domovskÃ½ch obrazovkÃ¡ch."
photo_copy_4="PÅ™idejte si mÄ› na JustUs, mÃ¡m fotky k odeslÃ¡nÃ­ na vaÅ¡i domovskou obrazovku. MÅ¯j prÅ¯kaz:"
photo_tips_4="OdeslÃ¡no na jejich domovskÃ© obrazovky! PÅ™idejte si dalÅ¡Ã­ pÅ™Ã¡tele a sdÃ­lejte svÃ© skuteÄnÃ© Å¾ivoty na svÃ½ch domovskÃ½ch obrazovkÃ¡ch."
photo_end_4="Å½Ã¡dnÃ© dalÅ¡Ã­ fotky. PÅ™idejte si dalÅ¡Ã­ pÅ™Ã¡tele a sdÃ­lejte svÃ© skuteÄnÃ© Å¾ivoty na svÃ½ch domovskÃ½ch obrazovkÃ¡ch."
photo_copy_5="PÅ™idejte si mÄ› na JustUs, novÃ© sociÃ¡lnÃ­ sÃ­ti widgetÅ¯! MÅ¯j prÅ¯kaz:"
photo_tips_5="OdeslÃ¡no na jejich domovskÃ© obrazovky! PÅ™idejte si dalÅ¡Ã­ pÅ™Ã¡tele a sdÃ­lejte svÃ© skuteÄnÃ© Å¾ivoty na svÃ½ch domovskÃ½ch obrazovkÃ¡ch."
photo_end_5="Å½Ã¡dnÃ© dalÅ¡Ã­ fotky. PozvÄ›te vÃ­ce pÅ™Ã¡tel, aby sdÃ­leli vaÅ¡e skuteÄnÃ© Å¾ivoty na vaÅ¡ich domovskÃ½ch obrazovkÃ¡ch."
photo_copy_6="PÅ™idejte si mÄ› na JustUs - sociÃ¡lnÃ­ sÃ­Å¥ Widget, vÅ¡e je pÅ™ipraveno kromÄ› vÃ¡s!"
photo_tips_6="OdeslÃ¡no na jejich domovskÃ© obrazovky! PozvÄ›te vÃ­ce pÅ™Ã¡tel, abyste s nimi sdÃ­leli svÃ© skuteÄnÃ© Å¾ivoty."
photo_end_6="Å½Ã¡dnÃ© dalÅ¡Ã­ fotky. PÅ™idejte si dalÅ¡Ã­ pÅ™Ã¡tele a sdÃ­lejte s nimi svÅ¯j skuteÄnÃ½ Å¾ivot."
photo_copy_7="PÅ™idejte si mÄ› na JustUs, vÅ¡e je pÅ™ipraveno kromÄ› vÃ¡s! MÅ¯j prÅ¯kaz:"
photo_tips_7="OdeslÃ¡no na jejich domovskÃ© obrazovky! PozvÄ›te vÃ­ce pÅ™Ã¡tel, abyste s nimi sdÃ­leli svÃ© skuteÄnÃ© Å¾ivoty."
photo_end_7="Å½Ã¡dnÃ© dalÅ¡Ã­ fotky. PÅ™idejte si dalÅ¡Ã­ pÅ™Ã¡tele a sdÃ­lejte s nimi svÅ¯j skuteÄnÃ½ Å¾ivot."
photo_copy_8="PÅ™idejte si mÄ› na JustUs - Widget Social Network, sdÃ­lejte se mnou skuteÄnÃ½ Å¾ivot! MÅ¯j prÅ¯kaz:"
photo_tips_8="OdeslÃ¡no na jejich domovskÃ© obrazovky! PozvÄ›te vÃ­ce pÅ™Ã¡tel, abyste s nimi sdÃ­leli svÃ© skuteÄnÃ© Å¾ivoty."
photo_end_8="Å½Ã¡dnÃ© dalÅ¡Ã­ fotky. PÅ™idejte si dalÅ¡Ã­ pÅ™Ã¡tele a sdÃ­lejte s nimi svÅ¯j skuteÄnÃ½ Å¾ivot."
photo_copy_9="PÅ™ijmÄ›te skuteÄnou fotografickou vÃ½zvu, pÅ™idejte si mÄ› na JustUs. MÅ¯j prÅ¯kaz:"
photo_tips_9="OdeslÃ¡no na jejich domovskÃ© obrazovky! PozvÄ›te vÃ­ce pÅ™Ã¡tel, abyste s nimi sdÃ­leli svÃ© skuteÄnÃ© Å¾ivoty."
photo_end_9="Å½Ã¡dnÃ© dalÅ¡Ã­ fotky. PÅ™idejte si dalÅ¡Ã­ pÅ™Ã¡tele a sdÃ­lejte s nimi svÅ¯j skuteÄnÃ½ Å¾ivot."
photo_copy_10="Chci, abyste byli na mÃ© domovskÃ© obrazovce, pÅ™idejte si mÄ› na JustUs. MÅ¯j prÅ¯kaz:"
photo_tips_10="OdeslÃ¡no na jejich domovskÃ© obrazovky! Bylo by zÃ¡bavnÄ›jÅ¡Ã­, kdybyste pÅ™idali vÃ­ce pÅ™Ã¡tel."
photo_end_10="Å½Ã¡dnÃ© dalÅ¡Ã­ fotky. PÅ™idejte si dalÅ¡Ã­ pÅ™Ã¡tele a sdÃ­lejte spolu svÃ© skuteÄnÃ© Å¾ivoty."
photo_copy_11="Chci, abyste byli na mÃ© domovskÃ© obrazovce, pÅ™idejte si mÄ› na JustUs. MÅ¯j prÅ¯kaz:"
photo_tips_11="OdeslÃ¡no na jejich domovskÃ© obrazovky! PÅ™idejte dalÅ¡Ã­ pÅ™Ã¡tele a posÃ­lejte jim fotografie na jejich domovskÃ© obrazovky."
photo_end_11="ZdÃ¡ se, Å¾e vÃ¡m doÅ¡ly fotografie pÅ™Ã¡tel! PÅ™idejte si dalÅ¡Ã­ pÅ™Ã¡tele, abyste mohli spoleÄnÄ› zaznamenat svÃ© skuteÄnÃ© Å¾ivoty."
photo_copy_12="BuÄ mÅ¯j pÅ™Ã­tel na ÃºvodnÃ­ obrazovce, pÅ™idej si mÄ› na JustUs. MÅ¯j prÅ¯kaz:"
photo_tips_12="OdeslÃ¡no na jejich domovskÃ© obrazovky! PozvÄ›te vÃ­ce pÅ™Ã¡tel na svou domovskou obrazovku a posÃ­lejte jim zÃ¡bavnÃ© fotografie!"
photo_end_12="ZdÃ¡ se, Å¾e vÃ¡m doÅ¡ly fotografie pÅ™Ã¡tel! PozvÄ›te vÃ­ce pÅ™Ã¡tel na svou domovskou obrazovku a posÃ­lejte jim zÃ¡bavnÃ© fotografie."
photo_copy_13="BuÄ mÅ¯j pÅ™Ã­tel na ÃºvodnÃ­ obrazovce, pÅ™idej si mÄ› na JustUs. MÅ¯j prÅ¯kaz:"
photo_tips_13="OdeslÃ¡no na jejich domovskÃ© obrazovky! Bylo by zÃ¡bavnÄ›jÅ¡Ã­, kdybyste pÅ™idali vÃ­ce pÅ™Ã¡tel na ÃºvodnÃ­ obrazovce."
photo_end_13="ZdÃ¡ se, Å¾e potÅ™ebujete vÃ­ce pÅ™Ã¡tel! PozvÄ›te vÃ­ce pÅ™Ã¡tel na svou domovskou obrazovku a posÃ­lejte jim zÃ¡bavnÃ© fotografie."
your_self_visible="ViditelnÃ© pouze pro mÄ›"
update_new_version="NovÃ¡ funkce duetu, pÅ™ijÄte upgradovat a zaÅ¾Ã­t to!"
