param_error="Eroare de parametru"
component_num_limit="Nu puteÈ›i, temporar, sÄƒ creaÈ›i mai multe grupuri."
friend_num_limit="Nu puteÈ›i adÄƒuga temporar mai mulÈ›i prieteni."
operation_error="OperaÈ›iunea a eÈ™uat. VÄƒ rugÄƒm sÄƒ Ã®ncercaÈ›i din nou mai tÃ¢rziu!"
char_limit="Caracterele pe care le-aÈ›i introdus depÄƒÈ™esc limita maximÄƒ de lungime. Maximul :number caractere."
first_name_limit="â€Numeleâ€ introdus depÄƒÈ™eÈ™te limita maximÄƒ de lungime. Maximul :number caractere."
last_name_limit="â€Prenumeleâ€ pe care l-aÈ›i introdus depÄƒÈ™eÈ™te limita maximÄƒ de lungime. Maximul :number caractere."
first_name_required="â€Numele de familieâ€ nu poate fi necompletat."
last_name_required="â€Prenumeleâ€ nu poate fi necompletat."
mobile_error="Eroare de format al numÄƒrului de telefon"
mobile_required="NumÄƒrul de telefon nu poate fi gol."
country_code_error="Eroare de cod de È›arÄƒ"
search_key="VÄƒ rugÄƒm sÄƒ introduceÈ›i un ID de utilizator valid sau un numÄƒr de telefon mobil."
is_add_friend="Cererea de adÄƒugare a prieteniei a fost trimisÄƒ."
system_error="Eroare de sistem"
msg_code_error="Eroare de format cod de verificare"
first_name_length="â€Numeleâ€ este prea lung."
friends_exist="Utilizator nu a fost gÄƒsit"
last_name_length="â€Prenumeleâ€ este prea lung."
content_length="Maximum 200 de caractere"
he_friend_num_limit="NumÄƒrul dvs. de prieteni sau al utilizatorului a atins limita."
sign_error="Verificarea semnaturii a eÈ™uat"
is_friends="Utilizatorul a fost prietenul tÄƒu."
sms_friend_tips="AdaugÄƒ-mÄƒ pe JustUs."
photo_tips="ÃncÄƒrcat cu succes! AdÄƒugaÈ›i mai mulÈ›i prieteni pentru a Ã®mpÄƒrtÄƒÈ™i viaÈ›a realÄƒ Ã®mpreunÄƒ"
message_limit="TrimiÈ›i mesaje text prea des. VÄƒ rugÄƒm sÄƒ Ã®ncercaÈ›i din nou mai tÃ¢rziu."
copy_friend_tips="AdaugÄƒ-mÄƒ pe JustUs."
no_add_friend_self="Nu te poÈ›i adÄƒuga ca prieten."
justus_slogan="SÄƒ Ã®nregistrÄƒm Ã®mpreunÄƒ viaÈ›a realÄƒ!"
justus_helper="Ghidul JustUs"
bind_mobile_error="NumÄƒrul de telefon a fost legat de alt cont."
bound_mobile="Legarea a eÈ™uat. VÄƒ rugÄƒm sÄƒ Ã®ncercaÈ›i din nou mai tÃ¢rziu."
not_add_self_friend="Nu te poÈ›i adÄƒuga ca prieten."
address_book_tips="SincronizeazÄƒ-È›i contactele pentru a gÄƒsi prieteni deja pe JustUs. Datele dvs. de contact vor fi trimise cÄƒtre JustUs pentru a vÄƒ Ã®mbunÄƒtÄƒÈ›i experienÈ›a È™i pentru a vÄƒ permite dvs. È™i altora sÄƒ vÄƒ gÄƒsiÈ›i prieteni."
follow_user="te-am urmarit!"
notification_friends=":name a devenit prietenul tÄƒu â€Doar noiâ€! ÃncearcÄƒ sÄƒ le trimiÈ›i fotografii!"
notification_like=":name doar te-a plÄƒcut!"
notification_comment=":name tocmai te-a comentat, vezi!"
notification_friend_apply=":name v-a trimis o cerere de prietenie."
notification_friend_send_picture=":name a postat o fotografie nouÄƒ."
notification_user_register="Vino È™i fÄƒ o fotografie! ÃnregistraÈ›i viaÈ›a realÄƒ Ã®mpreunÄƒ cu prietenii tÄƒi!"
notification_friend_register=":name este È™i pe JustUs. AdÄƒuga?"
notification_memory=":name, ai o nouÄƒ memorie."
notification_wait_add_friend=":name, prietenii tÄƒi aÈ™teaptÄƒ!"
notification_touch=":name È›i-a atins fotografiağŸ’“"
notification_follow_user=":name te-am urmarit!"
photo_copy_1="Te-am adÄƒugat pe (JustUs). DescÄƒrcaÈ›i aceastÄƒ aplicaÈ›ie pentru a permite cererea mea de prietenie.ID-ul meu:"
photo_tips_1="ÃncÄƒrcat cu succes! AdÄƒugaÈ›i mai mulÈ›i prieteni pentru a Ã®mpÄƒrtÄƒÈ™i viaÈ›a realÄƒ Ã®mpreunÄƒ"
photo_end_1="Gata cu momentele prietenilor. FaceÈ›i o fotografie sau adÄƒugaÈ›i mai mulÈ›i prieteni."
photo_copy_2="AdaugÄƒ-mÄƒ pe JustUs.ID-ul meu:"
photo_tips_2="ÃncÄƒrcat cu succes! AdÄƒugaÈ›i mai mulÈ›i prieteni pentru a Ã®mpÄƒrtÄƒÈ™i viaÈ›a realÄƒ Ã®mpreunÄƒ"
photo_end_2="Gata cu momentele prietenilor. FaceÈ›i o fotografie sau adÄƒugaÈ›i mai mulÈ›i prieteni."
photo_copy_3="AdaugÄƒ-mÄƒ pe JustUs ca sÄƒ putem partaja fotografii pe ecranul nostru de pornire. ID-ul meu:"
photo_tips_3="Trimis pe ecranele lor de pornire! AdÄƒugaÈ›i mai mulÈ›i prieteni pentru a vÄƒ Ã®mpÄƒrtÄƒÈ™i vieÈ›ile reale pe ecranele dvs. de pornire."
photo_end_3="Nu mai sunt fotografii. AdÄƒugaÈ›i mai mulÈ›i prieteni pentru a vÄƒ Ã®mpÄƒrtÄƒÈ™i vieÈ›ile reale pe ecranele dvs. de pornire."
photo_copy_4="AdaugÄƒ-mÄƒ pe JustUs, am fotografii de trimis pe ecranul tÄƒu de pornire. ID-ul meu:"
photo_tips_4="Trimis pe ecranele lor de pornire! AdÄƒugaÈ›i mai mulÈ›i prieteni pentru a vÄƒ Ã®mpÄƒrtÄƒÈ™i vieÈ›ile reale pe ecranele dvs. de pornire."
photo_end_4="Nu mai sunt fotografii. AdÄƒugaÈ›i mai mulÈ›i prieteni pentru a vÄƒ Ã®mpÄƒrtÄƒÈ™i vieÈ›ile reale pe ecranele dvs. de pornire."
photo_copy_5="AdaugÄƒ-mÄƒ pe JustUs, noua reÈ›ea socialÄƒ cu widget-uri! ID-ul meu:"
photo_tips_5="Trimis pe ecranele lor de pornire! AdÄƒugaÈ›i mai mulÈ›i prieteni pentru a vÄƒ Ã®mpÄƒrtÄƒÈ™i vieÈ›ile reale pe ecranele dvs. de pornire."
photo_end_5="Nu mai sunt fotografii. InvitaÈ›i mai mulÈ›i prieteni sÄƒ vÄƒ Ã®mpÄƒrtÄƒÈ™eascÄƒ vieÈ›ile reale pe ecranele dvs. de pornire."
photo_copy_6="AdaugÄƒ-mÄƒ pe JustUs - Widget Social Network, totul este gata, cu excepÈ›ia ta!"
photo_tips_6="Trimis pe ecranele lor de pornire! InvitaÈ›i mai mulÈ›i prieteni sÄƒ vÄƒ Ã®mpÄƒrtÄƒÈ™eascÄƒ viaÈ›a realÄƒ cu ei."
photo_end_6="Nu mai sunt fotografii. AdaugÄƒ mai mulÈ›i prieteni pentru a le Ã®mpÄƒrtÄƒÈ™i vieÈ›ile tale reale."
photo_copy_7="AdaugÄƒ-mÄƒ pe JustUs, totul este gata, cu excepÈ›ia ta! ID-ul meu:"
photo_tips_7="Trimis pe ecranele lor de pornire! InvitaÈ›i mai mulÈ›i prieteni sÄƒ vÄƒ Ã®mpÄƒrtÄƒÈ™eascÄƒ viaÈ›a realÄƒ cu ei."
photo_end_7="Nu mai sunt fotografii. AdaugÄƒ mai mulÈ›i prieteni pentru a le Ã®mpÄƒrtÄƒÈ™i vieÈ›ile tale reale."
photo_copy_8="AdaugÄƒ-mÄƒ pe JustUs - Widget Social Network, Ã®mpÄƒrtÄƒÈ™eÈ™te-mi viaÈ›a realÄƒ! ID-ul meu:"
photo_tips_8="Trimis pe ecranele lor de pornire! InvitaÈ›i mai mulÈ›i prieteni sÄƒ vÄƒ Ã®mpÄƒrtÄƒÈ™eascÄƒ viaÈ›a realÄƒ cu ei."
photo_end_8="Nu mai sunt fotografii. AdaugÄƒ mai mulÈ›i prieteni pentru a le Ã®mpÄƒrtÄƒÈ™i vieÈ›ile tale reale."
photo_copy_9="AcceptÄƒ provocarea foto din viaÈ›a realÄƒ, adaugÄƒ-mÄƒ pe JustUs. ID-ul meu:"
photo_tips_9="Trimis pe ecranele lor de pornire! InvitaÈ›i mai mulÈ›i prieteni sÄƒ vÄƒ Ã®mpÄƒrtÄƒÈ™eascÄƒ viaÈ›a realÄƒ cu ei."
photo_end_9="Nu mai sunt fotografii. AdaugÄƒ mai mulÈ›i prieteni pentru a le Ã®mpÄƒrtÄƒÈ™i vieÈ›ile tale reale."
photo_copy_10="Vreau sÄƒ fii pe ecranul meu de pornire, adaugÄƒ-mÄƒ pe JustUs. ID-ul meu:"
photo_tips_10="Trimis pe ecranele lor de pornire! Ar fi mai distractiv dacÄƒ adaugi mai mulÈ›i prieteni."
photo_end_10="Nu mai sunt fotografii. AdÄƒugaÈ›i mai mulÈ›i prieteni pentru a vÄƒ Ã®mpÄƒrtÄƒÈ™i vieÈ›ile reale Ã®mpreunÄƒ."
photo_copy_11="Vreau sÄƒ fii pe ecranul meu de pornire, adaugÄƒ-mÄƒ pe JustUs. ID-ul meu:"
photo_tips_11="Trimis pe ecranele lor de pornire! AdÄƒugaÈ›i mai mulÈ›i prieteni pentru a vÄƒ trimite fotografiile pe ecranele lor de pornire."
photo_end_11="Se pare cÄƒ ai rÄƒmas fÄƒrÄƒ fotografiile prietenilor! AdÄƒugaÈ›i mai mulÈ›i prieteni pentru a vÄƒ Ã®nregistra viaÈ›a realÄƒ Ã®mpreunÄƒ."
photo_copy_12="Fii prietenul meu pe ecranul de pornire, adaugÄƒ-mÄƒ pe JustUs. ID-ul meu:"
photo_tips_12="Trimis pe ecranele lor de pornire! InvitaÈ›i mai mulÈ›i prieteni pe ecranul dvs. de pornire È™i trimiteÈ›i-le fotografii distractive!"
photo_end_12="Se pare cÄƒ ai rÄƒmas fÄƒrÄƒ fotografiile prietenilor! InvitaÈ›i mai mulÈ›i prieteni pe ecranul dvs. de pornire È™i trimiteÈ›i-le fotografii distractive."
photo_copy_13="Fii prietenul meu pe ecranul de pornire, adaugÄƒ-mÄƒ pe JustUs. ID-ul meu:"
photo_tips_13="Trimis pe ecranele lor de pornire! Ar fi mai distractiv dacÄƒ adÄƒugaÈ›i mai mulÈ›i prieteni pe ecranul de pornire."
photo_end_13="Se pare cÄƒ ai nevoie de mai mulÈ›i prieteni! InvitaÈ›i mai mulÈ›i prieteni pe ecranul dvs. de pornire È™i trimiteÈ›i-le fotografii distractive."
your_self_visible="Vizibil doar pentru mine"
update_new_version="Noua funcÈ›ie duet, vÄƒ rugÄƒm sÄƒ veniÈ›i sÄƒ faceÈ›i upgrade È™i sÄƒ experimentaÈ›i!"
