param_error="砖转 驻专专"
component_num_limit="驻    爪专 拽爪转 住驻转."
friend_num_limit="驻    住祝 专 住驻."
operation_error="驻注 砖. 拽砖 住 砖 专 转专!"
char_limit="转 砖转 专 转 专 拽住转. 拽住 number: 转."
first_name_limit="砖 砖驻 砖转 专 转 专 拽住转. 拽住 number: 转."
last_name_limit="\"砖 驻专\" 砖转 专 转 专 拽住转. 拽住 number: 转."
first_name_required="砖 砖驻   转 专拽."
last_name_required="\"砖 驻专\"   转 专拽."
mobile_error="砖 驻专 住驻专 驻"
mobile_required="住驻专 驻   转 专拽."
country_code_error="砖转 拽 "
search_key="   砖转砖 拽  住驻专 ."
is_add_friend="拽砖转 专转 住祝 砖."
system_error="砖转 注专转"
msg_code_error="砖 驻专 拽 转"
first_name_length="砖 砖驻 专 ."
friends_exist="砖转砖  爪"
last_name_length="\"砖 驻专\" 专 ."
content_length="拽住 200 转"
he_friend_num_limit="住驻专 专 砖  砖 砖转砖 注 ."
sign_error="转 转 砖"
is_friends="砖转砖  专 砖."
sms_friend_tips="住祝 转 -JustUs."
photo_tips="注 爪! 住祝 专 住驻  拽  转  转"
message_limit="转 砖 注转 拽住 注转 拽专转 . 拽砖 住 砖 专 转专."
copy_friend_tips="住祝 转 -JustUs."
no_add_friend_self="转   住祝 转 注爪 专."
justus_slogan=" 转注 转  转 !"
justus_helper="专 JustUs"
bind_mobile_error="住驻专 驻 拽砖专 砖 专."
bound_mobile="专 砖. 拽砖 住 砖 专 转专."
not_add_self_friend="转   住祝 转 注爪 专."
address_book_tips="住专 转 砖 拽砖专 砖  爪 专 砖专 爪 -JustUs. 转 砖 拽砖专 砖 砖 -JustUs  砖驻专 转  砖 驻砖专  专 爪 专."
follow_user="注拽 专!"
notification_friends=":name 驻 专 \"专拽 \" 砖! 住 砖  转转!"
notification_like=":name 驻砖 转 转!"
notification_comment=":name 拽  注, 拽 转 !"
notification_friend_apply=":name 砖  拽砖转 专转."
notification_friend_send_picture=":name 驻专住 转 砖."
notification_user_register=" 爪! 拽 转  转 注 专 砖 !"
notification_friend_register=":name 爪  -JustUs. 职止住执祝?"
notification_memory=":name, 砖  专 砖."
notification_wait_add_friend=":name, 专 砖 !"
notification_touch=":name 拽砖 注 转 砖"
notification_follow_user=":name 注拽 专!"
photo_copy_1="住驻转 转 - (JustUs). 专 转 驻拽爪   驻砖专 转 拽砖转 专转 砖.ID:"
photo_tips_1="注 爪! 住祝 专 住驻  拽  转  转"
photo_end_1=" 转专 专注 砖 专. 爪 转  住祝 专 住驻."
photo_copy_2="住祝 转 -JustUs. ID:"
photo_tips_2="注 爪! 住祝 专 住驻  拽  转  转"
photo_end_2=" 转专 专注 砖 专. 爪 转  住祝 专 住驻."
photo_copy_3="住祝 转 -JustUs  砖 砖转祝 转转 住 转 砖. 转注转 转 砖:"
photo_tips_3="砖 住 转 砖! 住祝 专 住驻  砖转祝 转  转 住 转 砖."
photo_end_3=" 转专 转转. 住祝 专 住驻  砖转祝 转  转 住 转 砖."
photo_copy_4="住祝 转 -JustUs, 砖  转转 砖 住 转 砖. 转注转 转 砖:"
photo_tips_4="砖 住 转 砖! 住祝 专 住驻  砖转祝 转  转 住 转 砖."
photo_end_4=" 转专 转转. 住祝 专 住驻  砖转祝 转  转 住 转 砖."
photo_copy_5="住祝 转 -JustUs, 专砖转 专转转 ' 砖! 转注转 转 砖:"
photo_tips_5="砖 住 转 砖! 住祝 专 住驻  砖转祝 转  转 住 转 砖."
photo_end_5=" 转专 转转.  专 住驻 砖转祝 转  转 住 转 砖."
photo_copy_6="住祝 转 -JustUs - Widget Social Network,   抓 !"
photo_tips_6="砖 住 转 砖!  专 住驻 砖转祝 转 转  转."
photo_end_6=" 转专 转转. 住祝 专 住驻  砖转祝 转 转  转 砖."
photo_copy_7="住祝 转 -JustUs,   抓 ! 转注转 转 砖:"
photo_tips_7="砖 住 转 砖!  专 住驻 砖转祝 转 转  转."
photo_end_7=" 转专 转转. 住祝 专 住驻  砖转祝 转 转  转 砖."
photo_copy_8="住祝 转 -JustUs - Widget Social Network, 砖转祝 转 转  转! 转注转 转 砖:"
photo_tips_8="砖 住 转 砖!  专 住驻 砖转祝 转 转  转."
photo_end_8=" 转专 转转. 住祝 专 住驻  砖转祝 转 转  转 砖."
photo_copy_9="拽 转 转专 爪  转, 住祝 转 -JustUs. 转注转 转 砖:"
photo_tips_9="砖 住 转 砖!  专 住驻 砖转祝 转 转  转."
photo_end_9=" 转专 转转. 住祝 专 住驻  砖转祝 转 转  转 砖."
photo_copy_10=" 专爪 砖转 注 住 转 砖, 住祝 转 -JustUs. 转注转 转 砖:"
photo_tips_10="砖 住 转 砖!   转专 祝  转住祝 注 专."
photo_end_10=" 转专 转转. 住祝 专 住驻  砖转祝 转  转 ."
photo_copy_11=" 专爪 砖转 注 住 转 砖, 住祝 转 -JustUs. 转注转 转 砖:"
photo_tips_11="砖 住 转 砖! 住祝 专 住驻  砖 转 转转 砖 住 转 砖."
photo_end_11="专 砖专  转转 砖 专! 住祝 专 住驻  拽 转  转 ."
photo_copy_12=" 专 砖 住 转, 住祝 转 -JustUs. 转注转 转 砖:"
photo_tips_12="砖 住 转 砖!  专 住驻 住 转 砖 砖  转转 转!"
photo_end_12="专 砖专  转转 砖 专!  专 住驻 住 转 砖 砖  转转 转."
photo_copy_13=" 专 砖 住 转, 住祝 转 -JustUs. 转注转 转 砖:"
photo_tips_13="砖 住 转 砖!   转专 祝  转住祝 注 专 住 转."
photo_end_13="专 砖转 爪专 注 专!  专 住驻 住 转 砖 砖  转转 转."
your_self_visible=" 专拽 "
update_new_version="驻拽爪转  砖, 拽砖  砖专 转 转!"
