param_error="Pogre코ka parametra"
component_num_limit="Privremeno ne mo쬰te stvoriti vi코e grupa."
friend_num_limit="Privremeno ne mo쬰te dodati vi코e prijatelja."
operation_error="Operacija nije uspjela. Molimo poku코ajte ponovo kasnije!"
char_limit="Znakovi koje ste unijeli prema코uju ograni캜enje maksimalne duljine. Maksimalno :number znakova."
first_name_limit="Prezime koje ste unijeli prema코uje ograni캜enje maksimalne duljine. Maksimalno :number znakova."
last_name_limit="Ime koje ste unijeli prema코uje ograni캜enje maksimalne duljine. Maksimalno :number znakova."
first_name_required="Polje \"Prezime\" ne mo쬰 biti prazno."
last_name_required="Polje \"Ime\" ne mo쬰 biti prazno."
mobile_error="Pogre코ka formata telefonskog broja"
mobile_required="Telefonski broj ne mo쬰 biti prazan."
country_code_error="Pogre코ka koda zemlje"
search_key="Unesite va쬰캖i korisni캜ki ID ili broj mobitela."
is_add_friend="Zahtjev za dodavanje prijatelja je poslan."
system_error="Pogre코ka sustava"
msg_code_error="Pogre코ka formata kontrolnog koda"
first_name_length="Prezime je preduga캜ko."
friends_exist="Korisnik nije prona캠en"
last_name_length="Ime je preduga캜ko."
content_length="Maksimalno 200 znakova"
he_friend_num_limit="Va코 ili korisnikov broj prijatelja dosegao je ograni캜enje."
sign_error="Provjera potpisa nije uspjela"
is_friends="Korisnik vam je bio prijatelj."
sms_friend_tips="Dodaj me na JustUs."
photo_tips="Uspje코no preneseno! Dodajte jo코 prijatelja da zajedno dijelite stvarni 쬴vot"
message_limit="Pre캜esto 코aljete tekstualne poruke. Molimo poku코ajte ponovo kasnije."
copy_friend_tips="Dodaj me na JustUs."
no_add_friend_self="Ne mo쬰te se dodati kao prijatelja."
justus_slogan="Snimimo stvarni 쬴vot zajedno!"
justus_helper="JustUs vodi캜"
bind_mobile_error="Telefonski broj je vezan za drugi ra캜un."
bound_mobile="Povezivanje nije uspjelo. Molimo poku코ajte ponovo kasnije."
not_add_self_friend="Ne mo쬰te se dodati kao prijatelja."
address_book_tips="Sinkronizirajte svoje kontakte da biste prona코li prijatelje koji su ve캖 na JustUsu. Podaci o va코im kontaktima bit 캖e poslani JustUsu kako bismo pobolj코ali va코e iskustvo i omogu캖ili vama i drugima da prona캠u prijatelje."
follow_user="pratio te!"
notification_friends=":name je postao va코 prijatelj \"Samo mi\"! Poku코ajte im poslati fotografije!"
notification_like=":name ti se upravo svidio!"
notification_comment=":name vas je upravo komentirao, pogledajte!"
notification_friend_apply=":name vam je poslao zahtjev za prijateljstvo."
notification_friend_send_picture=":name je objavio novu fotografiju."
notification_user_register="Do캠ite i slikajte se! Snimite stvarni 쬴vot sa svojim prijateljima zajedno!"
notification_friend_register=":name je tako캠er na JustUsu. Dodati?"
notification_memory=":name, ima코 novu uspomenu."
notification_wait_add_friend=":name, tvoji prijatelji 캜ekaju!"
notification_touch=":name je dodirnuo va코u fotografiju游눕"
notification_follow_user=":name pratio te!"
photo_copy_1="Dodao sam vas na (JustUs). Preuzmite ovu aplikaciju da biste dopustili moj zahtjev za prijateljstvo.Moj ID:"
photo_tips_1="Uspje코no preneseno! Dodajte jo코 prijatelja da zajedno dijelite stvarni 쬴vot"
photo_end_1="Nema vi코e trenutaka prijatelja. Snimite fotografiju ili dodajte jo코 prijatelja."
photo_copy_2="Dodaj me na JustUs.Moj ID:"
photo_tips_2="Uspje코no preneseno! Dodajte jo코 prijatelja da zajedno dijelite stvarni 쬴vot"
photo_end_2="Nema vi코e trenutaka prijatelja. Snimite fotografiju ili dodajte jo코 prijatelja."
photo_copy_3="Dodajte me na JustUs kako bismo mogli dijeliti fotografije na na코em po캜etnom zaslonu. Moj ID:"
photo_tips_3="Poslano na njihove po캜etne zaslone! Dodajte jo코 prijatelja da podijelite svoje stvarne 쬴vote na svojim po캜etnim zaslonima."
photo_end_3="Nema vi코e fotografija. Dodajte jo코 prijatelja da podijelite svoje stvarne 쬴vote na svojim po캜etnim zaslonima."
photo_copy_4="Dodajte me na JustUs, imam fotografije za slanje na va코 po캜etni zaslon. Moj ID:"
photo_tips_4="Poslano na njihove po캜etne zaslone! Dodajte jo코 prijatelja da podijelite svoje stvarne 쬴vote na svojim po캜etnim zaslonima."
photo_end_4="Nema vi코e fotografija. Dodajte jo코 prijatelja da podijelite svoje stvarne 쬴vote na svojim po캜etnim zaslonima."
photo_copy_5="Dodaj me na JustUs, novu widget dru코tvenu mre쬿! Moj ID:"
photo_tips_5="Poslano na njihove po캜etne zaslone! Dodajte jo코 prijatelja da podijelite svoje stvarne 쬴vote na svojim po캜etnim zaslonima."
photo_end_5="Nema vi코e fotografija. Pozovite vi코e prijatelja da podijele svoje stvarne 쬴vote na va코im po캜etnim zaslonima."
photo_copy_6="Dodaj me na JustUs - Widget Social Network, sve je spremno osim tebe!"
photo_tips_6="Poslano na njihove po캜etne zaslone! Pozovite vi코e prijatelja da s njima podijelite svoje stvarne 쬴vote."
photo_end_6="Nema vi코e fotografija. Dodajte jo코 prijatelja da s njima podijelite svoje stvarne 쬴vote."
photo_copy_7="Dodaj me na JustUs, sve je spremno osim tebe! Moj ID:"
photo_tips_7="Poslano na njihove po캜etne zaslone! Pozovite vi코e prijatelja da s njima podijelite svoje stvarne 쬴vote."
photo_end_7="Nema vi코e fotografija. Dodajte jo코 prijatelja da s njima podijelite svoje stvarne 쬴vote."
photo_copy_8="Dodajte me na JustUs - Widget Social Network, podijelite stvarni 쬴vot sa mnom! Moj ID:"
photo_tips_8="Poslano na njihove po캜etne zaslone! Pozovite vi코e prijatelja da s njima podijelite svoje stvarne 쬴vote."
photo_end_8="Nema vi코e fotografija. Dodajte jo코 prijatelja da s njima podijelite svoje stvarne 쬴vote."
photo_copy_9="Prihvatite izazov iz stvarnog 쬴vota, dodajte me na JustUs. Moj ID:"
photo_tips_9="Poslano na njihove po캜etne zaslone! Pozovite vi코e prijatelja da s njima podijelite svoje stvarne 쬴vote."
photo_end_9="Nema vi코e fotografija. Dodajte jo코 prijatelja da s njima podijelite svoje stvarne 쬴vote."
photo_copy_10="콯elim da bude코 na mom po캜etnom zaslonu, dodaj me na JustUs. Moj ID:"
photo_tips_10="Poslano na njihove po캜etne zaslone! Bilo bi zabavnije ako dodate jo코 prijatelja."
photo_end_10="Nema vi코e fotografija. Dodajte jo코 prijatelja da zajedno podijelite svoje stvarne 쬴vote."
photo_copy_11="콯elim da bude코 na mom po캜etnom zaslonu, dodaj me na JustUs. Moj ID:"
photo_tips_11="Poslano na njihove po캜etne zaslone! Dodajte jo코 prijatelja da po코aljete svoje fotografije na njihove po캜etne zaslone."
photo_end_11="캛ini se da ste ostali bez fotografija prijatelja! Dodajte jo코 prijatelja kako biste zajedno snimili svoje stvarne 쬴vote."
photo_copy_12="Budi moj prijatelj na po캜etnom zaslonu, dodaj me na JustUs. Moj ID:"
photo_tips_12="Poslano na njihove po캜etne zaslone! Pozovite vi코e prijatelja na svoj po캜etni zaslon i po코aljite im zabavne fotografije!"
photo_end_12="캛ini se da ste ostali bez fotografija prijatelja! Pozovite vi코e prijatelja na po캜etni zaslon i po코aljite im zabavne fotografije."
photo_copy_13="Budi moj prijatelj na po캜etnom zaslonu, dodaj me na JustUs. Moj ID:"
photo_tips_13="Poslano na njihove po캜etne zaslone! Bilo bi zabavnije ako dodate vi코e prijatelja na po캜etni zaslon."
photo_end_13="캛ini se da trebate vi코e prijatelja! Pozovite vi코e prijatelja na po캜etni zaslon i po코aljite im zabavne fotografije."
your_self_visible="Vidljivo samo meni"
update_new_version="Nova funkcija dueta, do캠ite na nadogradnju i do쬴vite je!"
