param_error="BÅ‚Ä…d parametru"
component_num_limit="Tymczasowo nie moÅ¼esz tworzyÄ‡ kolejnych grup."
friend_num_limit="Tymczasowo nie moÅ¼esz dodaÄ‡ wiÄ™cej znajomych."
operation_error="Operacja nie powiodÅ‚a siÄ™. SprÃ³buj ponownie pÃ³Åºniej!"
char_limit="Wprowadzone znaki przekraczajÄ… maksymalny limit dÅ‚ugoÅ›ci. Maksymalnie :number znakÃ³w."
first_name_limit="Wprowadzone â€Nazwiskoâ€ przekracza maksymalny limit dÅ‚ugoÅ›ci. Maksymalnie :number znakÃ³w."
last_name_limit="Wpisane â€ImiÄ™â€ przekracza maksymalny limit dÅ‚ugoÅ›ci. Maksymalnie :number znakÃ³w."
first_name_required="Pole â€Nazwiskoâ€ nie moÅ¼e byÄ‡ puste."
last_name_required="Pole â€ImiÄ™â€ nie moÅ¼e byÄ‡ puste."
mobile_error="BÅ‚Ä…d formatu numeru telefonu"
mobile_required="Numer telefonu nie moÅ¼e byÄ‡ pusty."
country_code_error="BÅ‚Ä…d kodu kraju"
search_key="WprowadÅº prawidÅ‚owy identyfikator uÅ¼ytkownika lub numer telefonu komÃ³rkowego."
is_add_friend="ProÅ›ba o dodanie do znajomych zostaÅ‚a wysÅ‚ana."
system_error="BÅ‚Ä…d systemu"
msg_code_error="BÅ‚Ä…d formatu kodu weryfikacyjnego"
first_name_length="â€Nazwiskoâ€ jest za dÅ‚ugie."
friends_exist="UÅ¼ytkownik nie znaleziony"
last_name_length="â€ImiÄ™â€ jest za dÅ‚ugie."
content_length="Maksymalnie 200 znakÃ³w"
he_friend_num_limit="Liczba znajomych Twoich lub uÅ¼ytkownika osiÄ…gnÄ™Å‚a limit."
sign_error="Weryfikacja podpisu nieudana"
is_friends="UÅ¼ytkownik byÅ‚ twoim przyjacielem."
sms_friend_tips="Dodaj mnie na JustUs."
photo_tips="PrzesÅ‚ano pomyÅ›lnie! Dodaj wiÄ™cej znajomych, aby wspÃ³lnie dzieliÄ‡ prawdziwe Å¼ycie"
message_limit="Zbyt czÄ™sto wysyÅ‚asz SMS-y. SprÃ³buj ponownie pÃ³Åºniej."
copy_friend_tips="Dodaj mnie na JustUs."
no_add_friend_self="Nie moÅ¼esz dodaÄ‡ siebie jako przyjaciela."
justus_slogan="Nagrajmy razem prawdziwe Å¼ycie!"
justus_helper="Przewodnik JustUs"
bind_mobile_error="Numer telefonu zostaÅ‚ powiÄ…zany z innym kontem."
bound_mobile="WiÄ…zanie nie powiodÅ‚o siÄ™. SprÃ³buj ponownie pÃ³Åºniej."
not_add_self_friend="Nie moÅ¼esz dodaÄ‡ siebie jako przyjaciela."
address_book_tips="Zsynchronizuj swoje kontakty, aby znaleÅºÄ‡ znajomych juÅ¼ w JustUs. Twoje dane kontaktowe zostanÄ… wysÅ‚ane do JustUs, aby poprawiÄ‡ Twoje wraÅ¼enia i umoÅ¼liwiÄ‡ Tobie i innym znalezienie znajomych."
follow_user="za tobÄ…!"
notification_friends=":name zostaÅ‚ Twoim przyjacielem â€Tylko myâ€! SprÃ³buj wysÅ‚aÄ‡ im zdjÄ™cia!"
notification_like=":name po prostu ciÄ™ lubi!"
notification_comment=":name wÅ‚aÅ›nie CiÄ™ skomentowaÅ‚, sprawdÅº to!"
notification_friend_apply=":name wysÅ‚aÅ‚ Ci zaproszenie do znajomych."
notification_friend_send_picture=":name opublikowaÅ‚ nowe zdjÄ™cie."
notification_user_register="PrzyjdÅº i zrÃ³b zdjÄ™cie! Nagrywaj prawdziwe Å¼ycie razem ze znajomymi!"
notification_friend_register=":name jest rÃ³wnieÅ¼ na JustUs. DodaÄ‡?"
notification_memory=":name, masz nowe wspomnienie."
notification_wait_add_friend=":name, twoi przyjaciele czekajÄ…!"
notification_touch=":name dotknÄ…Å‚ twojego zdjÄ™ciağŸ’“"
notification_follow_user=":name za tobÄ…!"
photo_copy_1="DodaÅ‚em CiÄ™ na (JustUs). Pobierz tÄ™ aplikacjÄ™, aby umoÅ¼liwiÄ‡ mojÄ… proÅ›bÄ™ przyjaciela.MÃ³j dokument toÅ¼samoÅ›ci:"
photo_tips_1="PrzesÅ‚ano pomyÅ›lnie! Dodaj wiÄ™cej znajomych, aby wspÃ³lnie dzieliÄ‡ prawdziwe Å¼ycie"
photo_end_1="Å»adnych chwil z przyjaciÃ³Å‚mi. ZrÃ³b zdjÄ™cie lub dodaj wiÄ™cej znajomych."
photo_copy_2="Dodaj mnie na JustUs. MÃ³j dokument toÅ¼samoÅ›ci:"
photo_tips_2="PrzesÅ‚ano pomyÅ›lnie! Dodaj wiÄ™cej znajomych, aby wspÃ³lnie dzieliÄ‡ prawdziwe Å¼ycie"
photo_end_2="Å»adnych chwil z przyjaciÃ³Å‚mi. ZrÃ³b zdjÄ™cie lub dodaj wiÄ™cej znajomych."
photo_copy_3="Dodaj mnie do JustUs, abyÅ›my mogli udostÄ™pniaÄ‡ zdjÄ™cia na naszym ekranie gÅ‚Ã³wnym. MÃ³j dokument toÅ¼samoÅ›ci:"
photo_tips_3="WysÅ‚ane na ich ekrany gÅ‚Ã³wne! Dodaj wiÄ™cej znajomych, aby dzieliÄ‡ siÄ™ swoim prawdziwym Å¼yciem na ekranach gÅ‚Ã³wnych."
photo_end_3="Nigdy wiÄ™cej zdjÄ™Ä‡. Dodaj wiÄ™cej znajomych, aby dzieliÄ‡ siÄ™ swoim prawdziwym Å¼yciem na ekranach gÅ‚Ã³wnych."
photo_copy_4="Dodaj mnie w JustUs, mam zdjÄ™cia do wysÅ‚ania na TwÃ³j ekran gÅ‚Ã³wny. MÃ³j dokument toÅ¼samoÅ›ci:"
photo_tips_4="WysÅ‚ane na ich ekrany gÅ‚Ã³wne! Dodaj wiÄ™cej znajomych, aby dzieliÄ‡ siÄ™ swoim prawdziwym Å¼yciem na ekranach gÅ‚Ã³wnych."
photo_end_4="Nigdy wiÄ™cej zdjÄ™Ä‡. Dodaj wiÄ™cej znajomych, aby dzieliÄ‡ siÄ™ swoim prawdziwym Å¼yciem na ekranach gÅ‚Ã³wnych."
photo_copy_5="Dodaj mnie do JustUs, nowej sieci spoÅ‚ecznoÅ›ciowej z widÅ¼etami! MÃ³j dokument toÅ¼samoÅ›ci:"
photo_tips_5="WysÅ‚ane na ich ekrany gÅ‚Ã³wne! Dodaj wiÄ™cej znajomych, aby dzieliÄ‡ siÄ™ swoim prawdziwym Å¼yciem na ekranach gÅ‚Ã³wnych."
photo_end_5="Nigdy wiÄ™cej zdjÄ™Ä‡. ZaproÅ› wiÄ™cej znajomych do dzielenia siÄ™ Twoim prawdziwym Å¼yciem na ekranach gÅ‚Ã³wnych."
photo_copy_6="Dodaj mnie do JustUs - Widget Social Network, wszystko jest gotowe oprÃ³cz Ciebie!"
photo_tips_6="WysÅ‚ane na ich ekrany gÅ‚Ã³wne! ZaproÅ› wiÄ™cej znajomych, aby podzielili siÄ™ z nimi swoim prawdziwym Å¼yciem."
photo_end_6="Nigdy wiÄ™cej zdjÄ™Ä‡. Dodaj wiÄ™cej znajomych, aby dzieliÄ‡ siÄ™ z nimi swoim prawdziwym Å¼yciem."
photo_copy_7="Dodaj mnie do JustUs, wszystko jest gotowe oprÃ³cz Ciebie! MÃ³j dokument toÅ¼samoÅ›ci:"
photo_tips_7="WysÅ‚ane na ich ekrany gÅ‚Ã³wne! ZaproÅ› wiÄ™cej znajomych, aby podzielili siÄ™ z nimi swoim prawdziwym Å¼yciem."
photo_end_7="Nigdy wiÄ™cej zdjÄ™Ä‡. Dodaj wiÄ™cej znajomych, aby dzieliÄ‡ siÄ™ z nimi swoim prawdziwym Å¼yciem."
photo_copy_8="Dodaj mnie do JustUs - Widget Social Network, podziel siÄ™ ze mnÄ… prawdziwym Å¼yciem! MÃ³j dokument toÅ¼samoÅ›ci:"
photo_tips_8="WysÅ‚ane na ich ekrany gÅ‚Ã³wne! ZaproÅ› wiÄ™cej znajomych, aby podzielili siÄ™ z nimi swoim prawdziwym Å¼yciem."
photo_end_8="Nigdy wiÄ™cej zdjÄ™Ä‡. Dodaj wiÄ™cej znajomych, aby dzieliÄ‡ siÄ™ z nimi swoim prawdziwym Å¼yciem."
photo_copy_9="Zaakceptuj prawdziwe wyzwanie fotograficzne, Dodaj mnie na JustUs. MÃ³j dokument toÅ¼samoÅ›ci:"
photo_tips_9="WysÅ‚ane na ich ekrany gÅ‚Ã³wne! ZaproÅ› wiÄ™cej znajomych, aby podzielili siÄ™ z nimi swoim prawdziwym Å¼yciem."
photo_end_9="Nigdy wiÄ™cej zdjÄ™Ä‡. Dodaj wiÄ™cej znajomych, aby dzieliÄ‡ siÄ™ z nimi swoim prawdziwym Å¼yciem."
photo_copy_10="ChcÄ™, Å¼ebyÅ› byÅ‚ na moim ekranie gÅ‚Ã³wnym, dodaj mnie na JustUs. MÃ³j dokument toÅ¼samoÅ›ci:"
photo_tips_10="WysÅ‚ane na ich ekrany gÅ‚Ã³wne! ByÅ‚oby fajniej, gdybyÅ› dodaÅ‚ wiÄ™cej znajomych."
photo_end_10="Nigdy wiÄ™cej zdjÄ™Ä‡. Dodaj wiÄ™cej znajomych, aby dzieliÄ‡ siÄ™ swoim prawdziwym Å¼yciem."
photo_copy_11="ChcÄ™, Å¼ebyÅ› byÅ‚ na moim ekranie gÅ‚Ã³wnym, dodaj mnie na JustUs. MÃ³j dokument toÅ¼samoÅ›ci:"
photo_tips_11="WysÅ‚ane na ich ekrany gÅ‚Ã³wne! Dodaj wiÄ™cej znajomych, aby wysyÅ‚aÄ‡ zdjÄ™cia na ich ekrany gÅ‚Ã³wne."
photo_end_11="WyglÄ…da na to, Å¼e zabrakÅ‚o Ci zdjÄ™Ä‡ znajomych! Dodaj wiÄ™cej znajomych, aby nagraÄ‡ swoje wspÃ³lne Å¼ycie."
photo_copy_12="ZostaÅ„ moim przyjacielem na ekranie gÅ‚Ã³wnym, dodaj mnie w JustUs. MÃ³j dokument toÅ¼samoÅ›ci:"
photo_tips_12="WysÅ‚ane na ich ekrany gÅ‚Ã³wne! ZaproÅ› wiÄ™cej znajomych na swÃ³j ekran gÅ‚Ã³wny i wyÅ›lij im zabawne zdjÄ™cia!"
photo_end_12="WyglÄ…da na to, Å¼e zabrakÅ‚o Ci zdjÄ™Ä‡ znajomych! ZaproÅ› wiÄ™cej znajomych na ekran gÅ‚Ã³wny i wyÅ›lij im zabawne zdjÄ™cia."
photo_copy_13="ZostaÅ„ moim przyjacielem na ekranie gÅ‚Ã³wnym, dodaj mnie w JustUs. MÃ³j dokument toÅ¼samoÅ›ci:"
photo_tips_13="WysÅ‚ane na ich ekrany gÅ‚Ã³wne! ByÅ‚oby fajniej, gdybyÅ› dodaÅ‚ wiÄ™cej znajomych na ekranie gÅ‚Ã³wnym."
photo_end_13="WyglÄ…da na to, Å¼e potrzebujesz wiÄ™cej przyjaciÃ³Å‚! ZaproÅ› wiÄ™cej znajomych na ekran gÅ‚Ã³wny i wyÅ›lij im zabawne zdjÄ™cia."
your_self_visible="Widoczne tylko dla mnie"
update_new_version="Nowa funkcja duetu, przyjdÅº, aby jÄ… zaktualizowaÄ‡ i przeÅ¼yÄ‡!"
