param_error="Napaka parametra"
component_num_limit="Za캜asno ne morete ustvariti ve캜 skupin."
friend_num_limit="Za캜asno ne morete dodati ve캜 prijateljev."
operation_error="Operacija ni uspela. Prosim poskusite kasneje!"
char_limit="Znaki, ki ste jih vnesli, presegajo omejitev najve캜je dol쬴ne. Najve캜 :number znakov."
first_name_limit="Priimek, ki ste ga vnesli, presega omejitev najve캜je dol쬴ne. Najve캜je dovoljeno 코tevilo :number znakov."
last_name_limit="Ime, ki ste ga vnesli, presega omejitev najve캜je dol쬴ne. Najve캜je dovoljeno 코tevilo :number znakov."
first_name_required="Priimek ne sme biti prazen."
last_name_required="Polje 췉Ime춺 ne sme biti prazno."
mobile_error="Napaka v formatu telefonske 코tevilke"
mobile_required="Telefonska 코tevilka ne sme biti prazna."
country_code_error="Napaka kode dr쬬ve"
search_key="Vnesite veljaven ID uporabnika ali 코tevilko mobilnega telefona."
is_add_friend="Zahteva za dodajanje prijatelja je bila poslana."
system_error="Sistemska napaka"
msg_code_error="Napaka v formatu potrditvene kode"
first_name_length="Priimek je predolg."
friends_exist="Uporabnik ni najden"
last_name_length="Ime je predolgo."
content_length="Najve캜 200 znakov"
he_friend_num_limit="Va코e ali uporabnikovo 코tevilo prijateljev je doseglo omejitev."
sign_error="Preverjanje podpisa ni uspelo"
is_friends="Uporabnik je bil va코 prijatelj."
sms_friend_tips="Dodaj me na JustUs."
photo_tips="Uspe코no nalo쬰no! Dodajte ve캜 prijateljev, da si skupaj delite resni캜no 쬴vljenje"
message_limit="Prepogosto po코iljate besedilna sporo캜ila. Prosim poskusite kasneje."
copy_friend_tips="Dodaj me na JustUs."
no_add_friend_self="Ne morete se dodati kot prijatelja."
justus_slogan="Skupaj snemajmo resni캜no 쬴vljenje!"
justus_helper="Vodnik JustUs"
bind_mobile_error="Telefonska 코tevilka je bila vezana na drug ra캜un."
bound_mobile="Vezava ni uspela. Prosim poskusite kasneje."
not_add_self_friend="Ne more코 se dodati kot prijatelja."
address_book_tips="Sinhronizirajte svoje stike, da poi코캜ete prijatelje, ki so 쬰 na JustU. Podatki o va코ih stikih bodo poslani JustUsu, da izbolj코amo va코o izku코njo in omogo캜imo vam in drugim, da najdejo prijatelje."
follow_user="te spremljal!"
notification_friends=":name je postal va코 prijatelj 췉Samo mi춺! Poskusite jim poslati fotografije!"
notification_like=":name te je pravkar v코e캜!"
notification_comment=":name vas je pravkar komentirala, preverite!"
notification_friend_apply=":name vam je poslala pro코njo za prijateljstvo."
notification_friend_send_picture=":name je objavila novo fotografijo."
notification_user_register="Pridite in fotografirajte! Snemajte resni캜no 쬴vljenje s prijatelji skupaj!"
notification_friend_register=":name je tudi na JustU. dodaj?"
notification_memory=":name, ima코 nov spomin."
notification_wait_add_friend=":name, tvoji prijatelji 캜akajo!"
notification_touch=":name se je dotaknil tvoje fotografije游눕"
notification_follow_user=":name te spremljal!"
photo_copy_1="Dodal sem vas na (Samo mi). Prenesite to aplikacijo, da dovolite mojo pro코njo za prijateljstvo.moj ID:"
photo_tips_1="Uspe코no nalo쬰no! Dodajte ve캜 prijateljev, da si skupaj delite resni캜no 쬴vljenje"
photo_end_1="Ni캜 ve캜 trenutkov prijateljev. Posnemite fotografijo ali dodajte ve캜 prijateljev."
photo_copy_2="Dodaj me na JustUs.moj ID:"
photo_tips_2="Uspe코no nalo쬰no! Dodajte ve캜 prijateljev, da si skupaj delite resni캜no 쬴vljenje"
photo_end_2="Ni캜 ve캜 trenutkov prijateljev. Posnemite fotografijo ali dodajte ve캜 prijateljev."
photo_copy_3="Dodajte me na JustUs, da bomo lahko delili fotografije na doma캜em zaslonu. moj ID:"
photo_tips_3="Poslano na njihove doma캜e zaslone! Dodajte ve캜 prijateljev, da delite svoja resni캜na 쬴vljenja na doma캜ih zaslonih."
photo_end_3="Ni캜 ve캜 fotografij. Dodajte ve캜 prijateljev, da delite svoja resni캜na 쬴vljenja na doma캜ih zaslonih."
photo_copy_4="Dodajte me na JustUs, fotografije moram poslati na va코 doma캜i zaslon. moj ID:"
photo_tips_4="Poslano na njihove doma캜e zaslone! Dodajte ve캜 prijateljev, da delite svoja resni캜na 쬴vljenja na doma캜ih zaslonih."
photo_end_4="Ni캜 ve캜 fotografij. Dodajte ve캜 prijateljev, da delite svoja resni캜na 쬴vljenja na doma캜ih zaslonih."
photo_copy_5="Dodajte me na JustUs, novo dru쬬bno omre쬵e s pripomo캜ki! moj ID:"
photo_tips_5="Poslano na njihove doma캜e zaslone! Dodajte ve캜 prijateljev, da delite svoja resni캜na 쬴vljenja na doma캜ih zaslonih."
photo_end_5="Ni캜 ve캜 fotografij. Povabite ve캜 prijateljev, da delijo svoja resni캜na 쬴vljenja na va코ih doma캜ih zaslonih."
photo_copy_6="Dodaj me na JustUs - Widget Social Network, vse je pripravljeno, razen tebe!"
photo_tips_6="Poslano na njihove doma캜e zaslone! Povabite ve캜 prijateljev, da z njimi delite svoja resni캜na 쬴vljenja."
photo_end_6="Ni캜 ve캜 fotografij. Dodajte ve캜 prijateljev, da z njimi delite svoja resni캜na 쬴vljenja."
photo_copy_7="Dodaj me na JustUs, vse je pripravljeno razen tebe! moj ID:"
photo_tips_7="Poslano na njihove doma캜e zaslone! Povabite ve캜 prijateljev, da z njimi delite svoja resni캜na 쬴vljenja."
photo_end_7="Ni캜 ve캜 fotografij. Dodajte ve캜 prijateljev, da z njimi delite svoja resni캜na 쬴vljenja."
photo_copy_8="Dodajte me na JustUs - Widget Social Network, delite resni캜no 쬴vljenje z mano! moj ID:"
photo_tips_8="Poslano na njihove doma캜e zaslone! Povabite ve캜 prijateljev, da z njimi delite svoja resni캜na 쬴vljenja."
photo_end_8="Ni캜 ve캜 fotografij. Dodajte ve캜 prijateljev, da z njimi delite svoja resni캜na 쬴vljenja."
photo_copy_9="Sprejmite resni캜ni fotografski izziv, dodajte me na JustUs. moj ID:"
photo_tips_9="Poslano na njihove doma캜e zaslone! Povabite ve캜 prijateljev, da z njimi delite svoja resni캜na 쬴vljenja."
photo_end_9="Ni캜 ve캜 fotografij. Dodajte ve캜 prijateljev, da z njimi delite svoja resni캜na 쬴vljenja."
photo_copy_10="콯elim, da si na mojem doma캜em zaslonu, dodaj me na JustUs. moj ID:"
photo_tips_10="Poslano na njihove doma캜e zaslone! Bolj zabavno bi bilo, 캜e bi dodali ve캜 prijateljev."
photo_end_10="Ni캜 ve캜 fotografij. Dodajte ve캜 prijateljev, da skupaj delite svoja resni캜na 쬴vljenja."
photo_copy_11="콯elim, da si na mojem doma캜em zaslonu, dodaj me na JustUs. moj ID:"
photo_tips_11="Poslano na njihove doma캜e zaslone! Dodajte ve캜 prijateljev, da po코ljete svoje fotografije na njihove doma캜e zaslone."
photo_end_11="Zdi se, da vam je zmanjkalo fotografij prijateljev! Dodajte ve캜 prijateljev, da skupaj posnamete svoja resni캜na 쬴vljenja."
photo_copy_12="Bodi moj prijatelj na doma캜em zaslonu, dodaj me na JustUs. moj ID:"
photo_tips_12="Poslano na njihove doma캜e zaslone! Povabite ve캜 prijateljev na doma캜i zaslon in jim po코ljite zabavne fotografije!"
photo_end_12="Zdi se, da vam je zmanjkalo fotografij prijateljev! Povabite ve캜 prijateljev na doma캜i zaslon in jim po코ljite zabavne fotografije."
photo_copy_13="Bodi moj prijatelj na doma캜em zaslonu, dodaj me na JustUs. moj ID:"
photo_tips_13="Poslano na njihove doma캜e zaslone! Bolj zabavno bi bilo, 캜e dodate ve캜 prijateljev na doma캜em zaslonu."
photo_end_13="Zdi se, da potrebujete ve캜 prijateljev! Povabite ve캜 prijateljev na doma캜i zaslon in jim po코ljite zabavne fotografije."
your_self_visible="Vidno samo meni"
update_new_version="Nova funkcija dueta, pridite, da jo nadgradite in jo do쬴vite!"
