param_error="Lá»—i tham sá»‘"
component_num_limit="Báº¡n táº¡m thá»i khÃ´ng thá»ƒ táº¡o thÃªm nhÃ³m."
friend_num_limit="Báº¡n táº¡m thá»i khÃ´ng thá»ƒ thÃªm báº¡n bÃ¨."
operation_error="Lá»—i há»‡ thá»‘ng. Vui lÃ²ng thá»­ láº¡i sau!"
char_limit="CÃ¡c kÃ½ tá»± báº¡n Ä‘Ã£ nháº­p vÆ°á»£t quÃ¡ giá»›i háº¡n Ä‘á»™ dÃ i tá»‘i Ä‘a. Tá»‘i Ä‘a :number kÃ½ tá»±."
first_name_limit="Há» báº¡n Ä‘Ã£ nháº­p vÆ°á»£t quÃ¡ giá»›i háº¡n Ä‘á»™ dÃ i tá»‘i Ä‘a. Tá»‘i Ä‘a :number kÃ½ tá»±."
last_name_limit="TÃªn báº¡n Ä‘Ã£ nháº­p vÆ°á»£t quÃ¡ giá»›i háº¡n Ä‘á»™ dÃ i tá»‘i Ä‘a. Tá»‘i Ä‘a :number kÃ½ tá»±."
first_name_required="KhÃ´ng Ä‘Æ°á»£c Ä‘á»ƒ trá»‘ng \"Há»\"."
last_name_required="KhÃ´ng Ä‘Æ°á»£c Ä‘á»ƒ trá»‘ng \"TÃªn\"."
mobile_error="Lá»—i Ä‘á»‹nh dáº¡ng sá»‘ Ä‘iá»‡n thoáº¡i"
mobile_required="Sá»‘ Ä‘iá»‡n thoáº¡i khÃ´ng Ä‘Æ°á»£c Ä‘á»ƒ trá»‘ng."
country_code_error="Lá»—i mÃ£ quá»‘c gia"
search_key="Vui lÃ²ng nháº­p id ngÆ°á»i dÃ¹ng hoáº·c sá»‘ Ä‘iá»‡n thoáº¡i há»£p lá»‡."
is_add_friend="ThÃªm yÃªu cáº§u káº¿t báº¡n Ä‘Ã£ Ä‘Æ°á»£c gá»­i."
system_error="Lá»—i há»‡ thá»‘ng"
msg_code_error="Lá»—i Ä‘á»‹nh dáº¡ng mÃ£ xÃ¡c minh"
first_name_length="Há» quÃ¡ dÃ i."
friends_exist="KhÃ´ng tÃ¬m tháº¥y ngÆ°á»i dÃ¹ng"
last_name_length="TÃªn quÃ¡ dÃ i."
content_length="Tá»‘i Ä‘a 200 kÃ½ tá»±"
he_friend_num_limit="Sá»‘ lÆ°á»£ng báº¡n bÃ¨ cá»§a báº¡n hoáº·c ngÆ°á»i dÃ¹ng Ä‘Ã£ Ä‘áº¡t Ä‘áº¿n giá»›i háº¡n."
sign_error="XÃ¡c minh chá»¯ kÃ½ khÃ´ng thÃ nh cÃ´ng"
is_friends="NgÆ°á»i dÃ¹ng Ä‘Ã£ lÃ  báº¡n cá»§a báº¡n."
sms_friend_tips="ThÃªm tÃ´i trÃªn JustUs."
photo_tips="Táº£i lÃªn thÃ nh cÃ´ng! ThÃªm nhiá»u báº¡n bÃ¨ Ä‘á»ƒ chia sáº» cuá»™c sá»‘ng thá»±c cÃ¹ng nhau"
message_limit="Báº¡n gá»­i tin nháº¯n vÄƒn báº£n quÃ¡ thÆ°á»ng xuyÃªn. Vui lÃ²ng thá»­ láº¡i sau."
copy_friend_tips="ThÃªm tÃ´i trÃªn JustUs."
no_add_friend_self="Báº¡n khÃ´ng thá»ƒ thÃªm mÃ¬nh vÃ o lÃ m báº¡n."
justus_slogan="CÃ¹ng nhau ghi láº¡i cuá»™c sá»‘ng thá»±c táº¿ nhÃ©!"
justus_helper="HÆ°á»›ng dáº«n JustUs"
bind_mobile_error="Sá»‘ Ä‘iá»‡n thoáº¡i Ä‘Ã£ Ä‘Æ°á»£c liÃªn káº¿t vá»›i má»™t tÃ i khoáº£n khÃ¡c."
bound_mobile="RÃ ng buá»™c khÃ´ng thÃ nh cÃ´ng. Vui lÃ²ng thá»­ láº¡i sau."
not_add_self_friend="Báº¡n khÃ´ng thá»ƒ thÃªm mÃ¬nh lÃ m báº¡n."
address_book_tips="Äá»“ng bá»™ danh báº¡ cá»§a báº¡n Ä‘á»ƒ tÃ¬m báº¡n bÃ¨ Ä‘Ã£ cÃ³ trÃªn JustUs. Dá»¯ liá»‡u danh báº¡ cá»§a báº¡n sáº½ Ä‘Æ°á»£c gá»­i tá»›i JustUs Ä‘á»ƒ cáº£i thiá»‡n tráº£i nghiá»‡m cá»§a báº¡n vÃ  cho phÃ©p báº¡n vÃ  nhá»¯ng ngÆ°á»i khÃ¡c tÃ¬m kiáº¿m báº¡n bÃ¨."
follow_user="Ä‘Ã£ theo báº¡n!"
notification_friends=":name Ä‘Ã£ trá»Ÿ thÃ nh ngÆ°á»i báº¡n \"Chá»‰ vá»›i chÃºng tÃ´i\" cá»§a báº¡n! HÃ£y thá»­ gá»­i áº£nh cho há»!"
notification_like=":name chá»‰ thÃ­ch báº¡n!"
notification_comment=":name vá»«a nháº­n xÃ©t vá» báº¡n, hÃ£y kiá»ƒm tra!"
notification_friend_apply=":name Ä‘Ã£ gá»­i cho báº¡n má»™t yÃªu cáº§u káº¿t báº¡n."
notification_friend_send_picture=":name Ä‘Ã£ Ä‘Äƒng má»™t bá»©c áº£nh má»›i."
notification_user_register="HÃ£y Ä‘áº¿n vÃ  chá»¥p áº£nh! Ghi láº¡i cuá»™c sá»‘ng thá»±c vá»›i báº¡n bÃ¨ cá»§a báº¡n cÃ¹ng nhau!"
notification_friend_register=":name tÃªn cÅ©ng trÃªn JustUs. ThÃªm vÃ o?"
notification_memory=":name, báº¡n cÃ³ má»™t ká»· niá»‡m má»›i."
notification_wait_add_friend=":name, báº¡n bÃ¨ cá»§a báº¡n Ä‘ang Ä‘á»£i!"
notification_touch=":name cháº¡m vÃ o áº£nh cá»§a báº¡nğŸ’“"
notification_follow_user=":name Ä‘Ã£ theo báº¡n!"
photo_copy_1="TÃ´i Ä‘Ã£ thÃªm báº¡n vÃ o (JustUs). Táº£i xuá»‘ng á»©ng dá»¥ng nÃ y Ä‘á»ƒ cho phÃ©p yÃªu cáº§u káº¿t báº¡n cá»§a tÃ´i.MÃ£ sá»‘ cá»§a tÃ´i:"
photo_tips_1="Táº£i lÃªn thÃ nh cÃ´ng! ThÃªm nhiá»u báº¡n bÃ¨ Ä‘á»ƒ chia sáº» cuá»™c sá»‘ng thá»±c cÃ¹ng nhau"
photo_end_1="KhÃ´ng cÃ²n nhá»¯ng khoáº£nh kháº¯c cá»§a báº¡n bÃ¨. Chá»¥p áº£nh hoáº·c thÃªm báº¡n bÃ¨."
photo_copy_2="ThÃªm tÃ´i trÃªn JustUs.MÃ£ sá»‘ cá»§a tÃ´i:"
photo_tips_2="Táº£i lÃªn thÃ nh cÃ´ng! ThÃªm nhiá»u báº¡n bÃ¨ Ä‘á»ƒ chia sáº» cuá»™c sá»‘ng thá»±c cÃ¹ng nhau"
photo_end_2="KhÃ´ng cÃ²n nhá»¯ng khoáº£nh kháº¯c cá»§a báº¡n bÃ¨. Chá»¥p áº£nh hoáº·c thÃªm báº¡n bÃ¨."
photo_copy_3="ThÃªm tÃ´i vÃ o JustUs Ä‘á»ƒ chÃºng tÃ´i cÃ³ thá»ƒ chia sáº» áº£nh lÃªn mÃ n hÃ¬nh chÃ­nh cá»§a mÃ¬nh. MÃ£ sá»‘ cá»§a tÃ´i:"
photo_tips_3="Gá»­i Ä‘áº¿n mÃ n hÃ¬nh chÃ­nh cá»§a há»! ThÃªm nhiá»u báº¡n bÃ¨ Ä‘á»ƒ chia sáº» cuá»™c sá»‘ng thá»±c cá»§a báº¡n trÃªn mÃ n hÃ¬nh chÃ­nh."
photo_end_3="KhÃ´ng cÃ²n áº£nh ná»¯a. ThÃªm nhiá»u báº¡n bÃ¨ Ä‘á»ƒ chia sáº» cuá»™c sá»‘ng thá»±c cá»§a báº¡n trÃªn mÃ n hÃ¬nh chÃ­nh."
photo_copy_4="ThÃªm tÃ´i vÃ o JustUs, tÃ´i cÃ³ áº£nh Ä‘á»ƒ gá»­i Ä‘áº¿n mÃ n hÃ¬nh chÃ­nh cá»§a báº¡n. MÃ£ sá»‘ cá»§a tÃ´i:"
photo_tips_4="Gá»­i Ä‘áº¿n mÃ n hÃ¬nh chÃ­nh cá»§a há»! ThÃªm nhiá»u báº¡n bÃ¨ Ä‘á»ƒ chia sáº» cuá»™c sá»‘ng thá»±c cá»§a báº¡n trÃªn mÃ n hÃ¬nh chÃ­nh."
photo_end_4="KhÃ´ng cÃ²n áº£nh ná»¯a. ThÃªm nhiá»u báº¡n bÃ¨ Ä‘á»ƒ chia sáº» cuá»™c sá»‘ng thá»±c cá»§a báº¡n trÃªn mÃ n hÃ¬nh chÃ­nh."
photo_copy_5="ThÃªm tÃ´i trÃªn JustUs, máº¡ng xÃ£ há»™i tiá»‡n Ã­ch con má»›i! MÃ£ sá»‘ cá»§a tÃ´i:"
photo_tips_5="Gá»­i Ä‘áº¿n mÃ n hÃ¬nh chÃ­nh cá»§a há»! ThÃªm nhiá»u báº¡n bÃ¨ Ä‘á»ƒ chia sáº» cuá»™c sá»‘ng thá»±c cá»§a báº¡n trÃªn mÃ n hÃ¬nh chÃ­nh."
photo_end_5="KhÃ´ng cÃ²n áº£nh ná»¯a. Má»i thÃªm báº¡n bÃ¨ Ä‘á»ƒ chia sáº» cuá»™c sá»‘ng thá»±c cá»§a báº¡n trÃªn mÃ n hÃ¬nh chÃ­nh."
photo_copy_6="ThÃªm tÃ´i trÃªn JustUs - Máº¡ng xÃ£ há»™i tiá»‡n Ã­ch, táº¥t cáº£ Ä‘Ã£ sáºµn sÃ ng, ngoáº¡i trá»« báº¡n!"
photo_tips_6="Gá»­i Ä‘áº¿n mÃ n hÃ¬nh chÃ­nh cá»§a há»! Má»i thÃªm báº¡n bÃ¨ Ä‘á»ƒ chia sáº» cuá»™c sá»‘ng thá»±c cá»§a báº¡n vá»›i há»."
photo_end_6="KhÃ´ng cÃ²n áº£nh ná»¯a. ThÃªm nhiá»u báº¡n bÃ¨ Ä‘á»ƒ chia sáº» cuá»™c sá»‘ng thá»±c cá»§a báº¡n vá»›i há»."
photo_copy_7="ThÃªm tÃ´i vÃ o JustUs, táº¥t cáº£ Ä‘Ã£ sáºµn sÃ ng, ngoáº¡i trá»« báº¡n! MÃ£ sá»‘ cá»§a tÃ´i:"
photo_tips_7="Gá»­i Ä‘áº¿n mÃ n hÃ¬nh chÃ­nh cá»§a há»! Má»i thÃªm báº¡n bÃ¨ Ä‘á»ƒ chia sáº» cuá»™c sá»‘ng thá»±c cá»§a báº¡n vá»›i há»."
photo_end_7="KhÃ´ng cÃ²n áº£nh ná»¯a. ThÃªm nhiá»u báº¡n bÃ¨ Ä‘á»ƒ chia sáº» cuá»™c sá»‘ng thá»±c cá»§a báº¡n vá»›i há»."
photo_copy_8="ThÃªm tÃ´i trÃªn JustUs - Máº¡ng xÃ£ há»™i tiá»‡n Ã­ch, chia sáº» cuá»™c sá»‘ng thá»±c vá»›i tÃ´i! MÃ£ sá»‘ cá»§a tÃ´i:"
photo_tips_8="Gá»­i Ä‘áº¿n mÃ n hÃ¬nh chÃ­nh cá»§a há»! Má»i thÃªm báº¡n bÃ¨ Ä‘á»ƒ chia sáº» cuá»™c sá»‘ng thá»±c cá»§a báº¡n vá»›i há»."
photo_end_8="KhÃ´ng cÃ²n áº£nh ná»¯a. ThÃªm nhiá»u báº¡n bÃ¨ Ä‘á»ƒ chia sáº» cuá»™c sá»‘ng thá»±c cá»§a báº¡n vá»›i há»."
photo_copy_9="Cháº¥p nháº­n thá»­ thÃ¡ch chá»¥p áº£nh Ä‘á»i thá»±c, ThÃªm tÃ´i trÃªn JustUs. MÃ£ sá»‘ cá»§a tÃ´i:"
photo_tips_9="Gá»­i Ä‘áº¿n mÃ n hÃ¬nh chÃ­nh cá»§a há»! Má»i thÃªm báº¡n bÃ¨ Ä‘á»ƒ chia sáº» cuá»™c sá»‘ng thá»±c cá»§a báº¡n vá»›i há»."
photo_end_9="KhÃ´ng cÃ²n áº£nh ná»¯a. ThÃªm nhiá»u báº¡n bÃ¨ Ä‘á»ƒ chia sáº» cuá»™c sá»‘ng thá»±c cá»§a báº¡n vá»›i há»."
photo_copy_10="TÃ´i muá»‘n báº¡n á»Ÿ trÃªn mÃ n hÃ¬nh chÃ­nh cá»§a tÃ´i, hÃ£y thÃªm tÃ´i vÃ o JustUs. MÃ£ sá»‘ cá»§a tÃ´i:"
photo_tips_10="Gá»­i Ä‘áº¿n mÃ n hÃ¬nh chÃ­nh cá»§a há»! Sáº½ vui hÆ¡n náº¿u báº¡n cÃ³ thÃªm nhiá»u báº¡n bÃ¨."
photo_end_10="KhÃ´ng cÃ²n áº£nh ná»¯a. ThÃªm nhiá»u báº¡n bÃ¨ Ä‘á»ƒ chia sáº» cuá»™c sá»‘ng thá»±c cá»§a báº¡n vá»›i nhau."
photo_copy_11="TÃ´i muá»‘n báº¡n á»Ÿ trÃªn mÃ n hÃ¬nh chÃ­nh cá»§a tÃ´i, hÃ£y thÃªm tÃ´i vÃ o JustUs. MÃ£ sá»‘ cá»§a tÃ´i:"
photo_tips_11="Gá»­i Ä‘áº¿n mÃ n hÃ¬nh chÃ­nh cá»§a há»! ThÃªm nhiá»u báº¡n bÃ¨ Ä‘á»ƒ gá»­i áº£nh cá»§a báº¡n lÃªn mÃ n hÃ¬nh chÃ­nh cá»§a há»."
photo_end_11="CÃ³ váº» nhÆ° báº¡n Ä‘Ã£ háº¿t áº£nh cá»§a báº¡n bÃ¨! ThÃªm nhiá»u báº¡n bÃ¨ Ä‘á»ƒ ghi láº¡i cuá»™c sá»‘ng thá»±c cá»§a báº¡n cÃ¹ng nhau."
photo_copy_12="HÃ£y trá»Ÿ thÃ nh ngÆ°á»i báº¡n trÃªn mÃ n hÃ¬nh chÃ­nh cá»§a tÃ´i, thÃªm tÃ´i vÃ o JustUs. MÃ£ sá»‘ cá»§a tÃ´i:"
photo_tips_12="Gá»­i Ä‘áº¿n mÃ n hÃ¬nh chÃ­nh cá»§a há»! Má»i thÃªm báº¡n bÃ¨ vÃ o mÃ n hÃ¬nh chÃ­nh cá»§a báº¡n vÃ  gá»­i cho há» nhá»¯ng bá»©c áº£nh vui nhá»™n!"
photo_end_12="CÃ³ váº» nhÆ° báº¡n Ä‘Ã£ háº¿t áº£nh cá»§a báº¡n bÃ¨! Má»i thÃªm báº¡n bÃ¨ vÃ o mÃ n hÃ¬nh chÃ­nh cá»§a báº¡n vÃ  gá»­i cho há» nhá»¯ng bá»©c áº£nh vui nhá»™n."
photo_copy_13="HÃ£y trá»Ÿ thÃ nh ngÆ°á»i báº¡n trÃªn mÃ n hÃ¬nh chÃ­nh cá»§a tÃ´i, thÃªm tÃ´i vÃ o JustUs. MÃ£ sá»‘ cá»§a tÃ´i:"
photo_tips_13="Gá»­i Ä‘áº¿n mÃ n hÃ¬nh chÃ­nh cá»§a há»! Sáº½ vui hÆ¡n náº¿u báº¡n cÃ³ thÃªm nhiá»u ngÆ°á»i báº¡n trÃªn mÃ n hÃ¬nh chÃ­nh."
photo_end_13="CÃ³ váº» nhÆ° báº¡n cáº§n thÃªm báº¡n bÃ¨! Má»i thÃªm báº¡n bÃ¨ vÃ o mÃ n hÃ¬nh chÃ­nh cá»§a báº¡n vÃ  gá»­i cho há» nhá»¯ng bá»©c áº£nh vui nhá»™n."
your_self_visible="Chá»‰ hiá»ƒn thá»‹ vá»›i tÃ´i"
update_new_version="Chá»©c nÄƒng song ca má»›i, má»i cÃ¡c báº¡n vÃ o nÃ¢ng cáº¥p vÃ  tráº£i nghiá»‡m nhÃ©!"
