param_error="Chyba parametra"
component_num_limit="DoÄasne nemÃ´Å¾ete vytvoriÅ¥ ÄalÅ¡ie skupiny."
friend_num_limit="DoÄasne nemÃ´Å¾ete pridaÅ¥ ÄalÅ¡Ã­ch priateÄ¾ov."
operation_error="OperÃ¡cia zlyhala. SkÃºste neskÃ´r prosÃ­m!"
char_limit="ZadanÃ© znaky prekraÄujÃº maximÃ¡lnu dÄºÅ¾ku. MaximÃ¡lny poÄet :number znakov."
first_name_limit="ZadanÃ© â€Priezviskoâ€œ presahuje maximÃ¡lnu dÄºÅ¾ku. MaximÃ¡lny poÄet :number znakov."
last_name_limit="ZadanÃ© â€KrstnÃ© menoâ€œ prekraÄuje maximÃ¡lnu dÄºÅ¾ku. MaximÃ¡lny poÄet :number znakov."
first_name_required="Pole â€Priezviskoâ€œ nemÃ´Å¾e byÅ¥ prÃ¡zdne."
last_name_required="Pole â€KrstnÃ© menoâ€œ nemÃ´Å¾e byÅ¥ prÃ¡zdne."
mobile_error="Chyba formÃ¡tu telefÃ³nneho ÄÃ­sla"
mobile_required="TelefÃ³nne ÄÃ­slo nemÃ´Å¾e byÅ¥ prÃ¡zdne."
country_code_error="Chyba kÃ³du krajiny"
search_key="Zadajte platnÃ© ID pouÅ¾Ã­vateÄ¾a alebo mobilnÃ© ÄÃ­slo."
is_add_friend="Å½iadosÅ¥ o pridanie priateÄ¾stva bola odoslanÃ¡."
system_error="SystÃ©movÃ¡ chyba"
msg_code_error="Chyba formÃ¡tu overovacieho kÃ³du"
first_name_length="Priezvisko je prÃ­liÅ¡ dlhÃ©."
friends_exist="UÅ¾Ã­vateÄ¾ NenÃ¡jdenÃ½"
last_name_length="KrstnÃ© meno je prÃ­liÅ¡ dlhÃ©."
content_length="MaximÃ¡lne 200 znakov"
he_friend_num_limit="PoÄet vaÅ¡ich priateÄ¾ov alebo priateÄ¾ov pouÅ¾Ã­vateÄ¾a dosiahol limit."
sign_error="Overenie podpisu zlyhalo"
is_friends="PouÅ¾Ã­vateÄ¾ bol vaÅ¡Ã­m priateÄ¾om."
sms_friend_tips="Pridajte si ma na JustUs."
photo_tips="OdovzdanÃ© ÃºspeÅ¡ne! Pridajte si ÄalÅ¡Ã­ch priateÄ¾ov a zdieÄ¾ajte spolu skutoÄnÃ½ Å¾ivot"
message_limit="PrÃ­liÅ¡ Äasto posielate textovÃ© sprÃ¡vy. SkÃºste neskÃ´r prosÃ­m."
copy_friend_tips="Pridajte si ma na JustUs."
no_add_friend_self="NemÃ´Å¾ete sa pridaÅ¥ medzi priateÄ¾ov."
justus_slogan="Zaznamenajme spolu skutoÄnÃ½ Å¾ivot!"
justus_helper="Sprievodca JustUs"
bind_mobile_error="TelefÃ³nne ÄÃ­slo bolo zviazanÃ© s inÃ½m ÃºÄtom."
bound_mobile="VÃ¤zba zlyhala. SkÃºste neskÃ´r prosÃ­m."
not_add_self_friend="NemÃ´Å¾ete si pridaÅ¥ seba ako priateÄ¾a."
address_book_tips="Synchronizujte svoje kontakty, aby ste naÅ¡li priateÄ¾ov, ktorÃ­ uÅ¾ sÃº na JustUs. Ãšdaje o vaÅ¡ich kontaktoch sa odoÅ¡lÃº spoloÄnosti JustUs, aby sa zlepÅ¡ila vaÅ¡a skÃºsenosÅ¥ a umoÅ¾nili vÃ¡m a ostatnÃ½m nÃ¡jsÅ¥ priateÄ¾ov."
follow_user="nasledoval Å¥a!"
notification_friends=":name sa stal vaÅ¡Ã­m priateÄ¾om â€Iba myâ€œ! SkÃºste im poslaÅ¥ fotky!"
notification_like=":name sa vÃ¡m pÃ¡Äilo!"
notification_comment=":name vÃ¡s prÃ¡ve komentoval, pozrite si to!"
notification_friend_apply=":name vÃ¡m poslal Å¾iadosÅ¥ o priateÄ¾stvo."
notification_friend_send_picture=":name uverejnil novÃº fotku."
notification_user_register="PrÃ­Äte sa odfotiÅ¥! Zaznamenajte skutoÄnÃ½ Å¾ivot so svojimi priateÄ¾mi spolu!"
notification_friend_register=":name je aj na JustUs. PridaÅ¥?"
notification_memory=":name, mÃ¡te novÃº pamÃ¤Å¥."
notification_wait_add_friend=":name, vaÅ¡i priatelia ÄakajÃº!"
notification_touch=":name sa dotkol vaÅ¡ej fotkyğŸ’“"
notification_follow_user=":name nasledoval Å¥a!"
photo_copy_1="Pridal som si vÃ¡s na (JustUs). Stiahnite si tÃºto aplikÃ¡ciu, aby ste povolili moju Å¾iadosÅ¥ o priateÄ¾stvo.Moje ID:"
photo_tips_1="OdovzdanÃ© ÃºspeÅ¡ne! Pridajte si ÄalÅ¡Ã­ch priateÄ¾ov a zdieÄ¾ajte spolu skutoÄnÃ½ Å¾ivot"
photo_end_1="UÅ¾ Å¾iadne chvÃ­Ä¾ky priateÄ¾ov. OdfoÅ¥te sa alebo pridajte ÄalÅ¡Ã­ch priateÄ¾ov."
photo_copy_2="Pridajte si ma na JustUs.Moje ID:"
photo_tips_2="OdovzdanÃ© ÃºspeÅ¡ne! Pridajte si ÄalÅ¡Ã­ch priateÄ¾ov a zdieÄ¾ajte spolu skutoÄnÃ½ Å¾ivot"
photo_end_2="UÅ¾ Å¾iadne chvÃ­Ä¾ky priateÄ¾ov. OdfoÅ¥te sa alebo pridajte ÄalÅ¡Ã­ch priateÄ¾ov."
photo_copy_3="Pridajte si ma na JustUs, aby sme mohli zdieÄ¾aÅ¥ fotografie na domovskej obrazovke. Moje ID:"
photo_tips_3="OdoslanÃ© na ich plochy! Pridajte si ÄalÅ¡Ã­ch priateÄ¾ov a zdieÄ¾ajte svoje skutoÄnÃ© Å¾ivoty na svojich domovskÃ½ch obrazovkÃ¡ch."
photo_end_3="UÅ¾ Å¾iadne fotky. Pridajte si ÄalÅ¡Ã­ch priateÄ¾ov a zdieÄ¾ajte svoje skutoÄnÃ© Å¾ivoty na svojich domovskÃ½ch obrazovkÃ¡ch."
photo_copy_4="Pridajte si ma na JustUs, mÃ¡m fotky, ktorÃ© vÃ¡m poÅ¡lem na ÃºvodnÃº obrazovku. Moje ID:"
photo_tips_4="OdoslanÃ© na ich plochy! Pridajte si ÄalÅ¡Ã­ch priateÄ¾ov a zdieÄ¾ajte svoje skutoÄnÃ© Å¾ivoty na svojich domovskÃ½ch obrazovkÃ¡ch."
photo_end_4="UÅ¾ Å¾iadne fotky. Pridajte si ÄalÅ¡Ã­ch priateÄ¾ov a zdieÄ¾ajte svoje skutoÄnÃ© Å¾ivoty na svojich domovskÃ½ch obrazovkÃ¡ch."
photo_copy_5="Pridajte si ma na JustUs, novej sociÃ¡lnej sieti s widgetmi! Moje ID:"
photo_tips_5="OdoslanÃ© na ich plochy! Pridajte si ÄalÅ¡Ã­ch priateÄ¾ov a zdieÄ¾ajte svoje skutoÄnÃ© Å¾ivoty na svojich domovskÃ½ch obrazovkÃ¡ch."
photo_end_5="UÅ¾ Å¾iadne fotky. Pozvite viac priateÄ¾ov, aby zdieÄ¾ali vaÅ¡e skutoÄnÃ© Å¾ivoty na vaÅ¡ich domovskÃ½ch obrazovkÃ¡ch."
photo_copy_6="Pridajte si ma na JustUs - Widget Social Network, vÅ¡etko je pripravenÃ© okrem vÃ¡s!"
photo_tips_6="OdoslanÃ© na ich plochy! Pozvite ÄalÅ¡Ã­ch priateÄ¾ov, aby ste s nimi zdieÄ¾ali svoje skutoÄnÃ© Å¾ivoty."
photo_end_6="UÅ¾ Å¾iadne fotky. Pridajte si ÄalÅ¡Ã­ch priateÄ¾ov a zdieÄ¾ajte s nimi svoje skutoÄnÃ© Å¾ivoty."
photo_copy_7="Pridajte si ma na JustUs, vÅ¡etko je pripravenÃ© okrem vÃ¡s! Moje ID:"
photo_tips_7="OdoslanÃ© na ich plochy! Pozvite ÄalÅ¡Ã­ch priateÄ¾ov, aby ste s nimi zdieÄ¾ali svoje skutoÄnÃ© Å¾ivoty."
photo_end_7="UÅ¾ Å¾iadne fotky. Pridajte si ÄalÅ¡Ã­ch priateÄ¾ov a zdieÄ¾ajte s nimi svoje skutoÄnÃ© Å¾ivoty."
photo_copy_8="Pridajte si ma na JustUs - Widget Social Network, zdieÄ¾ajte so mnou skutoÄnÃ½ Å¾ivot! Moje ID:"
photo_tips_8="OdoslanÃ© na ich plochy! Pozvite ÄalÅ¡Ã­ch priateÄ¾ov, aby ste s nimi zdieÄ¾ali svoje skutoÄnÃ© Å¾ivoty."
photo_end_8="UÅ¾ Å¾iadne fotky. Pridajte si ÄalÅ¡Ã­ch priateÄ¾ov a zdieÄ¾ajte s nimi svoje skutoÄnÃ© Å¾ivoty."
photo_copy_9="Prijmite skutoÄnÃº fotografickÃº vÃ½zvu, pridajte si ma na JustUs. Moje ID:"
photo_tips_9="OdoslanÃ© na ich plochy! Pozvite ÄalÅ¡Ã­ch priateÄ¾ov, aby ste s nimi zdieÄ¾ali svoje skutoÄnÃ© Å¾ivoty."
photo_end_9="UÅ¾ Å¾iadne fotky. Pridajte si ÄalÅ¡Ã­ch priateÄ¾ov a zdieÄ¾ajte s nimi svoje skutoÄnÃ© Å¾ivoty."
photo_copy_10="Chcem, aby si bol na mojej domovskej obrazovke, pridal si ma na JustUs. Moje ID:"
photo_tips_10="OdoslanÃ© na ich plochy! Bolo by zÃ¡bavnejÅ¡ie, keby ste pridali viac priateÄ¾ov."
photo_end_10="UÅ¾ Å¾iadne fotky. Pridajte si ÄalÅ¡Ã­ch priateÄ¾ov a zdieÄ¾ajte spolu svoje skutoÄnÃ© Å¾ivoty."
photo_copy_11="Chcem, aby si bol na mojej domovskej obrazovke, pridal si ma na JustUs. Moje ID:"
photo_tips_11="OdoslanÃ© na ich plochy! Pridajte si ÄalÅ¡Ã­ch priateÄ¾ov, aby ste im mohli poslaÅ¥ fotografie na ich domovskÃ© obrazovky."
photo_end_11="ZdÃ¡ sa, Å¾e vÃ¡m doÅ¡li fotografie priateÄ¾ov! Pridajte si ÄalÅ¡Ã­ch priateÄ¾ov, aby ste spolu zaznamenali svoje skutoÄnÃ© Å¾ivoty."
photo_copy_12="BuÄ mojÃ­m priateÄ¾om na Ãºvodnej obrazovke, pridaj si ma na JustUs. Moje ID:"
photo_tips_12="OdoslanÃ© na ich plochy! Pozvite ÄalÅ¡Ã­ch priateÄ¾ov na svoju domovskÃº obrazovku a poÅ¡lite im zÃ¡bavnÃ© fotografie!"
photo_end_12="ZdÃ¡ sa, Å¾e vÃ¡m doÅ¡li fotografie priateÄ¾ov! Pozvite ÄalÅ¡Ã­ch priateÄ¾ov na svoju domovskÃº obrazovku a poÅ¡lite im zÃ¡bavnÃ© fotografie."
photo_copy_13="BuÄ mojÃ­m priateÄ¾om na Ãºvodnej obrazovke, pridaj si ma na JustUs. Moje ID:"
photo_tips_13="OdoslanÃ© na ich plochy! Bolo by zÃ¡bavnejÅ¡ie, keby ste pridali viac priateÄ¾ov na Ãºvodnej obrazovke."
photo_end_13="ZdÃ¡ sa, Å¾e potrebujete viac priateÄ¾ov! Pozvite ÄalÅ¡Ã­ch priateÄ¾ov na svoju domovskÃº obrazovku a poÅ¡lite im zÃ¡bavnÃ© fotografie."
your_self_visible="ViditeÄ¾nÃ© iba pre mÅˆa"
update_new_version="NovÃ¡ funkcia duet, prÃ­Äte si ju upgradovaÅ¥ a zaÅ¾iÅ¥!"
